INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'Manchester City (ENG)', 'SSC Napoli (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'Villarreal CF (ESP)', 'Bayern München (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'Bayern München (GER)', 'Manchester City (ENG)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'SSC Napoli (ITA)', 'Villarreal CF (ESP)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'Manchester City (ENG)', 'Villarreal CF (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'SSC Napoli (ITA)', 'Bayern München (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'Bayern München (GER)', 'SSC Napoli (ITA)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'Villarreal CF (ESP)', 'Manchester City (ENG)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'Bayern München (GER)', 'Villarreal CF (ESP)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'SSC Napoli (ITA)', 'Manchester City (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'Manchester City (ENG)', 'Bayern München (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group A', 'Villarreal CF (ESP)', 'SSC Napoli (ITA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'Lille OSC (FRA)', 'CSKA Moskva (RUS)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'Inter (ITA)', 'Trabzonspor (TUR)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'CSKA Moskva (RUS)', 'Inter (ITA)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'Trabzonspor (TUR)', 'Lille OSC (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'CSKA Moskva (RUS)', 'Trabzonspor (TUR)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'Lille OSC (FRA)', 'Inter (ITA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'Trabzonspor (TUR)', 'CSKA Moskva (RUS)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'Inter (ITA)', 'Lille OSC (FRA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'CSKA Moskva (RUS)', 'Lille OSC (FRA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'Trabzonspor (TUR)', 'Inter (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'Inter (ITA)', 'CSKA Moskva (RUS)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group B', 'Lille OSC (FRA)', 'Trabzonspor (TUR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'FC Basel 1893 (SUI)', 'Oţelul Galaţi (ROU)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'SL Benfica (POR)', 'Manchester United (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'Manchester United (ENG)', 'FC Basel 1893 (SUI)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'Oţelul Galaţi (ROU)', 'SL Benfica (POR)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'FC Basel 1893 (SUI)', 'SL Benfica (POR)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'Oţelul Galaţi (ROU)', 'Manchester United (ENG)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'Manchester United (ENG)', 'Oţelul Galaţi (ROU)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'SL Benfica (POR)', 'FC Basel 1893 (SUI)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'Manchester United (ENG)', 'SL Benfica (POR)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'Oţelul Galaţi (ROU)', 'FC Basel 1893 (SUI)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'FC Basel 1893 (SUI)', 'Manchester United (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group C', 'SL Benfica (POR)', 'Oţelul Galaţi (ROU)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'AFC Ajax (NED)', 'Olympique Lyonnais (FRA)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'Dinamo Zagreb (CRO)', 'Real Madrid (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'Olympique Lyonnais (FRA)', 'Dinamo Zagreb (CRO)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'Real Madrid (ESP)', 'AFC Ajax (NED)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'Dinamo Zagreb (CRO)', 'AFC Ajax (NED)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'Real Madrid (ESP)', 'Olympique Lyonnais (FRA)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'AFC Ajax (NED)', 'Dinamo Zagreb (CRO)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'Olympique Lyonnais (FRA)', 'Real Madrid (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'Olympique Lyonnais (FRA)', 'AFC Ajax (NED)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'Real Madrid (ESP)', 'Dinamo Zagreb (CRO)', '6-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'AFC Ajax (NED)', 'Real Madrid (ESP)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group D', 'Dinamo Zagreb (CRO)', 'Olympique Lyonnais (FRA)', '1-7');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'Chelsea FC (ENG)', 'Bayer Leverkusen (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'KRC Genk (BEL)', 'Valencia CF (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'Bayer Leverkusen (GER)', 'KRC Genk (BEL)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'Valencia CF (ESP)', 'Chelsea FC (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'Bayer Leverkusen (GER)', 'Valencia CF (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'Chelsea FC (ENG)', 'KRC Genk (BEL)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'KRC Genk (BEL)', 'Chelsea FC (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'Valencia CF (ESP)', 'Bayer Leverkusen (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'Bayer Leverkusen (GER)', 'Chelsea FC (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'Valencia CF (ESP)', 'KRC Genk (BEL)', '7-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'Chelsea FC (ENG)', 'Valencia CF (ESP)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group E', 'KRC Genk (BEL)', 'Bayer Leverkusen (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Borussia Dortmund (GER)', 'Arsenal FC (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Olympiakos Piraeus (GRE)', 'Olympique Marseille (FRA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Arsenal FC (ENG)', 'Olympiakos Piraeus (GRE)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Olympique Marseille (FRA)', 'Borussia Dortmund (GER)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Olympiakos Piraeus (GRE)', 'Borussia Dortmund (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Olympique Marseille (FRA)', 'Arsenal FC (ENG)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Arsenal FC (ENG)', 'Olympique Marseille (FRA)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Borussia Dortmund (GER)', 'Olympiakos Piraeus (GRE)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Arsenal FC (ENG)', 'Borussia Dortmund (GER)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Olympique Marseille (FRA)', 'Olympiakos Piraeus (GRE)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Borussia Dortmund (GER)', 'Olympique Marseille (FRA)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group F', 'Olympiakos Piraeus (GRE)', 'Arsenal FC (ENG)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'APOEL Nikosia (CYP)', 'Zenit St. Petersburg (RUS)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'FC Porto (POR)', 'Shakhtar Donetsk (UKR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'Zenit St. Petersburg (RUS)', 'FC Porto (POR)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'Shakhtar Donetsk (UKR)', 'APOEL Nikosia (CYP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'FC Porto (POR)', 'APOEL Nikosia (CYP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'Shakhtar Donetsk (UKR)', 'Zenit St. Petersburg (RUS)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'Zenit St. Petersburg (RUS)', 'Shakhtar Donetsk (UKR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'APOEL Nikosia (CYP)', 'FC Porto (POR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'Zenit St. Petersburg (RUS)', 'APOEL Nikosia (CYP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'Shakhtar Donetsk (UKR)', 'FC Porto (POR)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'APOEL Nikosia (CYP)', 'Shakhtar Donetsk (UKR)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group G', 'FC Porto (POR)', 'Zenit St. Petersburg (RUS)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'FC Barcelona (ESP)', 'AC Milan (ITA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'Viktoria Plzeň (CZE)', 'BATE Borisov (BLR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'AC Milan (ITA)', 'Viktoria Plzeň (CZE)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'BATE Borisov (BLR)', 'FC Barcelona (ESP)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'AC Milan (ITA)', 'BATE Borisov (BLR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'FC Barcelona (ESP)', 'Viktoria Plzeň (CZE)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'BATE Borisov (BLR)', 'AC Milan (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'Viktoria Plzeň (CZE)', 'FC Barcelona (ESP)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'BATE Borisov (BLR)', 'Viktoria Plzeň (CZE)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'AC Milan (ITA)', 'FC Barcelona (ESP)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'FC Barcelona (ESP)', 'BATE Borisov (BLR)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Group H', 'Viktoria Plzeň (CZE)', 'AC Milan (ITA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'Olympique Lyonnais (FRA)', 'APOEL Nikosia (CYP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'Bayer Leverkusen (GER)', 'FC Barcelona (ESP)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'Zenit St. Petersburg (RUS)', 'SL Benfica (POR)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'AC Milan (ITA)', 'Arsenal FC (ENG)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'CSKA Moskva (RUS)', 'Real Madrid (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'SSC Napoli (ITA)', 'Chelsea FC (ENG)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'FC Basel 1893 (SUI)', 'Bayern München (GER)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'Olympique Marseille (FRA)', 'Inter (ITA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'Arsenal FC (ENG)', 'AC Milan (ITA)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'SL Benfica (POR)', 'Zenit St. Petersburg (RUS)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'APOEL Nikosia (CYP)', 'Olympique Lyonnais (FRA)', '1-0(4-3)');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'FC Barcelona (ESP)', 'Bayer Leverkusen (GER)', '7-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'Bayern München (GER)', 'FC Basel 1893 (SUI)', '7-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'Inter (ITA)', 'Olympique Marseille (FRA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'Chelsea FC (ENG)', 'SSC Napoli (ITA)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Round of 16', 'Real Madrid (ESP)', 'CSKA Moskva (RUS)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Quarterfinals', 'APOEL Nikosia (CYP)', 'Real Madrid (ESP)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Quarterfinals', 'SL Benfica (POR)', 'Chelsea FC (ENG)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Quarterfinals', 'Olympique Marseille (FRA)', 'Bayern München (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Quarterfinals', 'AC Milan (ITA)', 'FC Barcelona (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Quarterfinals', 'Bayern München (GER)', 'Olympique Marseille (FRA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Quarterfinals', 'FC Barcelona (ESP)', 'AC Milan (ITA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Quarterfinals', 'Real Madrid (ESP)', 'APOEL Nikosia (CYP)', '5-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Quarterfinals', 'Chelsea FC (ENG)', 'SL Benfica (POR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Semifinals', 'Bayern München (GER)', 'Real Madrid (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Semifinals', 'Chelsea FC (ENG)', 'FC Barcelona (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Semifinals', 'FC Barcelona (ESP)', 'Chelsea FC (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Semifinals', 'Real Madrid (ESP)', 'Bayern München (GER)', '2-1(1-3)');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2011-2012', 'Final', 'Bayern München (GER)', 'Chelsea FC (ENG)', '1-1(3-4)');