INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'Paris Saint-Germain (FRA)', 'Dinamo Kiev (UKR)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'Dinamo Zagreb (CRO)', 'FC Porto (POR)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'FC Porto (POR)', 'Paris Saint-Germain (FRA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'Dinamo Kiev (UKR)', 'Dinamo Zagreb (CRO)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'FC Porto (POR)', 'Dinamo Kiev (UKR)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'Dinamo Zagreb (CRO)', 'Paris Saint-Germain (FRA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'Dinamo Kiev (UKR)', 'FC Porto (POR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'Paris Saint-Germain (FRA)', 'Dinamo Zagreb (CRO)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'Dinamo Kiev (UKR)', 'Paris Saint-Germain (FRA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'FC Porto (POR)', 'Dinamo Zagreb (CRO)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'Paris Saint-Germain (FRA)', 'FC Porto (POR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group A', 'Dinamo Zagreb (CRO)', 'Dinamo Kiev (UKR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'Olympiakos Piraeus (GRE)', 'FC Schalke 04 (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'Montpellier HSC (FRA)', 'Arsenal FC (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'Arsenal FC (ENG)', 'Olympiakos Piraeus (GRE)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'FC Schalke 04 (GER)', 'Montpellier HSC (FRA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'Arsenal FC (ENG)', 'FC Schalke 04 (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'Montpellier HSC (FRA)', 'Olympiakos Piraeus (GRE)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'FC Schalke 04 (GER)', 'Arsenal FC (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'Olympiakos Piraeus (GRE)', 'Montpellier HSC (FRA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'FC Schalke 04 (GER)', 'Olympiakos Piraeus (GRE)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'Arsenal FC (ENG)', 'Montpellier HSC (FRA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'Olympiakos Piraeus (GRE)', 'Arsenal FC (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group B', 'Montpellier HSC (FRA)', 'FC Schalke 04 (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'AC Milan (ITA)', 'RSC Anderlecht (BEL)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'Málaga CF (ESP)', 'Zenit St. Petersburg (RUS)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'Zenit St. Petersburg (RUS)', 'AC Milan (ITA)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'RSC Anderlecht (BEL)', 'Málaga CF (ESP)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'Zenit St. Petersburg (RUS)', 'RSC Anderlecht (BEL)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'Málaga CF (ESP)', 'AC Milan (ITA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'RSC Anderlecht (BEL)', 'Zenit St. Petersburg (RUS)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'AC Milan (ITA)', 'Málaga CF (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'Zenit St. Petersburg (RUS)', 'Málaga CF (ESP)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'RSC Anderlecht (BEL)', 'AC Milan (ITA)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'AC Milan (ITA)', 'Zenit St. Petersburg (RUS)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group C', 'Málaga CF (ESP)', 'RSC Anderlecht (BEL)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'Real Madrid (ESP)', 'Manchester City (ENG)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'Borussia Dortmund (GER)', 'AFC Ajax (NED)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'AFC Ajax (NED)', 'Real Madrid (ESP)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'Manchester City (ENG)', 'Borussia Dortmund (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'AFC Ajax (NED)', 'Manchester City (ENG)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'Borussia Dortmund (GER)', 'Real Madrid (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'Manchester City (ENG)', 'AFC Ajax (NED)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'Real Madrid (ESP)', 'Borussia Dortmund (GER)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'Manchester City (ENG)', 'Real Madrid (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'AFC Ajax (NED)', 'Borussia Dortmund (GER)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'Real Madrid (ESP)', 'AFC Ajax (NED)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group D', 'Borussia Dortmund (GER)', 'Manchester City (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'Chelsea FC (ENG)', 'Juventus (ITA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'Shakhtar Donetsk (UKR)', 'FC Nordsjælland (DEN)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'Juventus (ITA)', 'Shakhtar Donetsk (UKR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'FC Nordsjælland (DEN)', 'Chelsea FC (ENG)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'Shakhtar Donetsk (UKR)', 'Chelsea FC (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'FC Nordsjælland (DEN)', 'Juventus (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'Chelsea FC (ENG)', 'Shakhtar Donetsk (UKR)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'Juventus (ITA)', 'FC Nordsjælland (DEN)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'Juventus (ITA)', 'Chelsea FC (ENG)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'FC Nordsjælland (DEN)', 'Shakhtar Donetsk (UKR)', '2-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'Shakhtar Donetsk (UKR)', 'Juventus (ITA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group E', 'Chelsea FC (ENG)', 'FC Nordsjælland (DEN)', '6-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'Bayern München (GER)', 'Valencia CF (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'Lille OSC (FRA)', 'BATE Borisov (BLR)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'Valencia CF (ESP)', 'Lille OSC (FRA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'BATE Borisov (BLR)', 'Bayern München (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'Lille OSC (FRA)', 'Bayern München (GER)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'BATE Borisov (BLR)', 'Valencia CF (ESP)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'Bayern München (GER)', 'Lille OSC (FRA)', '6-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'Valencia CF (ESP)', 'BATE Borisov (BLR)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'BATE Borisov (BLR)', 'Lille OSC (FRA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'Valencia CF (ESP)', 'Bayern München (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'Lille OSC (FRA)', 'Valencia CF (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group F', 'Bayern München (GER)', 'BATE Borisov (BLR)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'FC Barcelona (ESP)', 'Spartak Moskva (RUS)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'Celtic FC (SCO)', 'SL Benfica (POR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'Spartak Moskva (RUS)', 'Celtic FC (SCO)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'SL Benfica (POR)', 'FC Barcelona (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'Spartak Moskva (RUS)', 'SL Benfica (POR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'FC Barcelona (ESP)', 'Celtic FC (SCO)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'SL Benfica (POR)', 'Spartak Moskva (RUS)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'Celtic FC (SCO)', 'FC Barcelona (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'Spartak Moskva (RUS)', 'FC Barcelona (ESP)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'SL Benfica (POR)', 'Celtic FC (SCO)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'FC Barcelona (ESP)', 'SL Benfica (POR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group G', 'Celtic FC (SCO)', 'Spartak Moskva (RUS)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'Manchester United (ENG)', 'Galatasaray (TUR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'Sporting Braga (POR)', 'CFR Cluj (ROU)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'Galatasaray (TUR)', 'Sporting Braga (POR)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'CFR Cluj (ROU)', 'Manchester United (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'Manchester United (ENG)', 'Sporting Braga (POR)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'Galatasaray (TUR)', 'CFR Cluj (ROU)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'Sporting Braga (POR)', 'Manchester United (ENG)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'CFR Cluj (ROU)', 'Galatasaray (TUR)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'Galatasaray (TUR)', 'Manchester United (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'CFR Cluj (ROU)', 'Sporting Braga (POR)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'Sporting Braga (POR)', 'Galatasaray (TUR)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Group H', 'Manchester United (ENG)', 'CFR Cluj (ROU)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Celtic FC (SCO)', 'Juventus (ITA)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Valencia CF (ESP)', 'Paris Saint-Germain (FRA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Shakhtar Donetsk (UKR)', 'Borussia Dortmund (GER)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Real Madrid (ESP)', 'Manchester United (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Arsenal FC (ENG)', 'Bayern München (GER)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'FC Porto (POR)', 'Málaga CF (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Galatasaray (TUR)', 'FC Schalke 04 (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'AC Milan (ITA)', 'FC Barcelona (ESP)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Borussia Dortmund (GER)', 'Shakhtar Donetsk (UKR)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Manchester United (ENG)', 'Real Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Juventus (ITA)', 'Celtic FC (SCO)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Paris Saint-Germain (FRA)', 'Valencia CF (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'FC Schalke 04 (GER)', 'Galatasaray (TUR)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'FC Barcelona (ESP)', 'AC Milan (ITA)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Bayern München (GER)', 'Arsenal FC (ENG)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Round of 16', 'Málaga CF (ESP)', 'FC Porto (POR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Quarterfinals', 'Paris Saint-Germain (FRA)', 'FC Barcelona (ESP)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Quarterfinals', 'Bayern München (GER)', 'Juventus (ITA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Quarterfinals', 'Málaga CF (ESP)', 'Borussia Dortmund (GER)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Quarterfinals', 'Real Madrid (ESP)', 'Galatasaray (TUR)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Quarterfinals', 'Borussia Dortmund (GER)', 'Málaga CF (ESP)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Quarterfinals', 'Galatasaray (TUR)', 'Real Madrid (ESP)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Quarterfinals', 'FC Barcelona (ESP)', 'Paris Saint-Germain (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Quarterfinals', 'Juventus (ITA)', 'Bayern München (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Semifinals', 'Bayern München (GER)', 'FC Barcelona (ESP)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Semifinals', 'Borussia Dortmund (GER)', 'Real Madrid (ESP)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Semifinals', 'Real Madrid (ESP)', 'Borussia Dortmund (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Semifinals', 'FC Barcelona (ESP)', 'Bayern München (GER)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2012-2013', 'Final', 'Borussia Dortmund (GER)', 'Bayern München (GER)', '1-2');