INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Manchester United (ENG)', 'Bayer Leverkusen (GER)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Real Sociedad (ESP)', 'Shakhtar Donetsk (UKR)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Shakhtar Donetsk (UKR)', 'Manchester United (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Bayer Leverkusen (GER)', 'Real Sociedad (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Bayer Leverkusen (GER)', 'Shakhtar Donetsk (UKR)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Manchester United (ENG)', 'Real Sociedad (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Shakhtar Donetsk (UKR)', 'Bayer Leverkusen (GER)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Real Sociedad (ESP)', 'Manchester United (ENG)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Bayer Leverkusen (GER)', 'Manchester United (ENG)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Shakhtar Donetsk (UKR)', 'Real Sociedad (ESP)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Manchester United (ENG)', 'Shakhtar Donetsk (UKR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group A', 'Real Sociedad (ESP)', 'Bayer Leverkusen (GER)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'Galatasaray (TUR)', 'Real Madrid (ESP)', '1-6');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'FC København (DEN)', 'Juventus (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'Juventus (ITA)', 'Galatasaray (TUR)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'Real Madrid (ESP)', 'FC København (DEN)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'Real Madrid (ESP)', 'Juventus (ITA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'Galatasaray (TUR)', 'FC København (DEN)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'Juventus (ITA)', 'Real Madrid (ESP)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'FC København (DEN)', 'Galatasaray (TUR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'Real Madrid (ESP)', 'Galatasaray (TUR)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'Juventus (ITA)', 'FC København (DEN)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'FC København (DEN)', 'Real Madrid (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group B', 'Galatasaray (TUR)', 'Juventus (ITA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'Olympiakos Piraeus (GRE)', 'Paris Saint-Germain (FRA)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'SL Benfica (POR)', 'RSC Anderlecht (BEL)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'Paris Saint-Germain (FRA)', 'SL Benfica (POR)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'RSC Anderlecht (BEL)', 'Olympiakos Piraeus (GRE)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'RSC Anderlecht (BEL)', 'Paris Saint-Germain (FRA)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'SL Benfica (POR)', 'Olympiakos Piraeus (GRE)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'Paris Saint-Germain (FRA)', 'RSC Anderlecht (BEL)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'Olympiakos Piraeus (GRE)', 'SL Benfica (POR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'RSC Anderlecht (BEL)', 'SL Benfica (POR)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'Paris Saint-Germain (FRA)', 'Olympiakos Piraeus (GRE)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'SL Benfica (POR)', 'Paris Saint-Germain (FRA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group C', 'Olympiakos Piraeus (GRE)', 'RSC Anderlecht (BEL)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'Bayern München (GER)', 'CSKA Moskva (RUS)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'Viktoria Plzeň (CZE)', 'Manchester City (ENG)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'CSKA Moskva (RUS)', 'Viktoria Plzeň (CZE)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'Manchester City (ENG)', 'Bayern München (GER)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'CSKA Moskva (RUS)', 'Manchester City (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'Bayern München (GER)', 'Viktoria Plzeň (CZE)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'Manchester City (ENG)', 'CSKA Moskva (RUS)', '5-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'Viktoria Plzeň (CZE)', 'Bayern München (GER)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'CSKA Moskva (RUS)', 'Bayern München (GER)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'Manchester City (ENG)', 'Viktoria Plzeň (CZE)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'Bayern München (GER)', 'Manchester City (ENG)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group D', 'Viktoria Plzeň (CZE)', 'CSKA Moskva (RUS)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'Chelsea FC (ENG)', 'FC Basel 1893 (SUI)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'FC Schalke 04 (GER)', 'FC Steaua Bucureşti (ROU)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'FC Basel 1893 (SUI)', 'FC Schalke 04 (GER)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'FC Steaua Bucureşti (ROU)', 'Chelsea FC (ENG)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'FC Schalke 04 (GER)', 'Chelsea FC (ENG)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'FC Steaua Bucureşti (ROU)', 'FC Basel 1893 (SUI)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'Chelsea FC (ENG)', 'FC Schalke 04 (GER)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'FC Basel 1893 (SUI)', 'FC Steaua Bucureşti (ROU)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'FC Basel 1893 (SUI)', 'Chelsea FC (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'FC Steaua Bucureşti (ROU)', 'FC Schalke 04 (GER)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'FC Schalke 04 (GER)', 'FC Basel 1893 (SUI)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group E', 'Chelsea FC (ENG)', 'FC Steaua Bucureşti (ROU)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'Olympique Marseille (FRA)', 'Arsenal FC (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'SSC Napoli (ITA)', 'Borussia Dortmund (GER)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'Borussia Dortmund (GER)', 'Olympique Marseille (FRA)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'Arsenal FC (ENG)', 'SSC Napoli (ITA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'Arsenal FC (ENG)', 'Borussia Dortmund (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'Olympique Marseille (FRA)', 'SSC Napoli (ITA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'Borussia Dortmund (GER)', 'Arsenal FC (ENG)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'SSC Napoli (ITA)', 'Olympique Marseille (FRA)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'Arsenal FC (ENG)', 'Olympique Marseille (FRA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'Borussia Dortmund (GER)', 'SSC Napoli (ITA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'Olympique Marseille (FRA)', 'Borussia Dortmund (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group F', 'SSC Napoli (ITA)', 'Arsenal FC (ENG)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'Atlético Madrid (ESP)', 'Zenit St. Petersburg (RUS)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'Austria Wien (AUT)', 'FC Porto (POR)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'Zenit St. Petersburg (RUS)', 'Austria Wien (AUT)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'FC Porto (POR)', 'Atlético Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'FC Porto (POR)', 'Zenit St. Petersburg (RUS)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'Austria Wien (AUT)', 'Atlético Madrid (ESP)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'Zenit St. Petersburg (RUS)', 'FC Porto (POR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'Atlético Madrid (ESP)', 'Austria Wien (AUT)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'Zenit St. Petersburg (RUS)', 'Atlético Madrid (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'FC Porto (POR)', 'Austria Wien (AUT)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'Atlético Madrid (ESP)', 'FC Porto (POR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group G', 'Austria Wien (AUT)', 'Zenit St. Petersburg (RUS)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'FC Barcelona (ESP)', 'AFC Ajax (NED)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'AC Milan (ITA)', 'Celtic FC (SCO)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'AFC Ajax (NED)', 'AC Milan (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'Celtic FC (SCO)', 'FC Barcelona (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'AC Milan (ITA)', 'FC Barcelona (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'Celtic FC (SCO)', 'AFC Ajax (NED)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'FC Barcelona (ESP)', 'AC Milan (ITA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'AFC Ajax (NED)', 'Celtic FC (SCO)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'AFC Ajax (NED)', 'FC Barcelona (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'Celtic FC (SCO)', 'AC Milan (ITA)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'AC Milan (ITA)', 'AFC Ajax (NED)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Group H', 'FC Barcelona (ESP)', 'Celtic FC (SCO)', '6-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Manchester City (ENG)', 'FC Barcelona (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Bayer Leverkusen (GER)', 'Paris Saint-Germain (FRA)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'AC Milan (ITA)', 'Atlético Madrid (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Arsenal FC (ENG)', 'Bayern München (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Zenit St. Petersburg (RUS)', 'Borussia Dortmund (GER)', '2-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Olympiakos Piraeus (GRE)', 'Manchester United (ENG)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Galatasaray (TUR)', 'Chelsea FC (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'FC Schalke 04 (GER)', 'Real Madrid (ESP)', '1-6');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Atlético Madrid (ESP)', 'AC Milan (ITA)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Bayern München (GER)', 'Arsenal FC (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'FC Barcelona (ESP)', 'Manchester City (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Paris Saint-Germain (FRA)', 'Bayer Leverkusen (GER)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Chelsea FC (ENG)', 'Galatasaray (TUR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Real Madrid (ESP)', 'FC Schalke 04 (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Manchester United (ENG)', 'Olympiakos Piraeus (GRE)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Round of 16', 'Borussia Dortmund (GER)', 'Zenit St. Petersburg (RUS)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Quarterfinals', 'FC Barcelona (ESP)', 'Atlético Madrid (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Quarterfinals', 'Manchester United (ENG)', 'Bayern München (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Quarterfinals', 'Real Madrid (ESP)', 'Borussia Dortmund (GER)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Quarterfinals', 'Paris Saint-Germain (FRA)', 'Chelsea FC (ENG)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Quarterfinals', 'Borussia Dortmund (GER)', 'Real Madrid (ESP)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Quarterfinals', 'Chelsea FC (ENG)', 'Paris Saint-Germain (FRA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Quarterfinals', 'Atlético Madrid (ESP)', 'FC Barcelona (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Quarterfinals', 'Bayern München (GER)', 'Manchester United (ENG)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Semifinals', 'Atlético Madrid (ESP)', 'Chelsea FC (ENG)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Semifinals', 'Real Madrid (ESP)', 'Bayern München (GER)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Semifinals', 'Bayern München (GER)', 'Real Madrid (ESP)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Semifinals', 'Chelsea FC (ENG)', 'Atlético Madrid (ESP)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2013-2014', 'Final', 'Real Madrid (ESP)', 'Atlético Madrid (ESP)', '4-1');