INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Olympiakos Piraeus (GRE)', 'Atlético Madrid (ESP)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Juventus (ITA)', 'Malmö FF (SWE)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Atlético Madrid (ESP)', 'Juventus (ITA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Malmö FF (SWE)', 'Olympiakos Piraeus (GRE)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Atlético Madrid (ESP)', 'Malmö FF (SWE)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Olympiakos Piraeus (GRE)', 'Juventus (ITA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Malmö FF (SWE)', 'Atlético Madrid (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Juventus (ITA)', 'Olympiakos Piraeus (GRE)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Atlético Madrid (ESP)', 'Olympiakos Piraeus (GRE)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Malmö FF (SWE)', 'Juventus (ITA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Juventus (ITA)', 'Atlético Madrid (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group A', 'Olympiakos Piraeus (GRE)', 'Malmö FF (SWE)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'Real Madrid (ESP)', 'FC Basel 1893 (SUI)', '5-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'Liverpool FC (ENG)', 'PFC Ludogorets Razgrad (BUL)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'FC Basel 1893 (SUI)', 'Liverpool FC (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'PFC Ludogorets Razgrad (BUL)', 'Real Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'PFC Ludogorets Razgrad (BUL)', 'FC Basel 1893 (SUI)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'Liverpool FC (ENG)', 'Real Madrid (ESP)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'FC Basel 1893 (SUI)', 'PFC Ludogorets Razgrad (BUL)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'Real Madrid (ESP)', 'Liverpool FC (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'FC Basel 1893 (SUI)', 'Real Madrid (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'PFC Ludogorets Razgrad (BUL)', 'Liverpool FC (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'Liverpool FC (ENG)', 'FC Basel 1893 (SUI)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group B', 'Real Madrid (ESP)', 'PFC Ludogorets Razgrad (BUL)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'AS Monaco (FRA)', 'Bayer Leverkusen (GER)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'SL Benfica (POR)', 'Zenit St. Petersburg (RUS)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'Zenit St. Petersburg (RUS)', 'AS Monaco (FRA)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'Bayer Leverkusen (GER)', 'SL Benfica (POR)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'AS Monaco (FRA)', 'SL Benfica (POR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'Bayer Leverkusen (GER)', 'Zenit St. Petersburg (RUS)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'Zenit St. Petersburg (RUS)', 'Bayer Leverkusen (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'SL Benfica (POR)', 'AS Monaco (FRA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'Zenit St. Petersburg (RUS)', 'SL Benfica (POR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'Bayer Leverkusen (GER)', 'AS Monaco (FRA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'AS Monaco (FRA)', 'Zenit St. Petersburg (RUS)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group C', 'SL Benfica (POR)', 'Bayer Leverkusen (GER)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'Borussia Dortmund (GER)', 'Arsenal FC (ENG)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'Galatasaray (TUR)', 'RSC Anderlecht (BEL)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'Arsenal FC (ENG)', 'Galatasaray (TUR)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'RSC Anderlecht (BEL)', 'Borussia Dortmund (GER)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'RSC Anderlecht (BEL)', 'Arsenal FC (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'Galatasaray (TUR)', 'Borussia Dortmund (GER)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'Arsenal FC (ENG)', 'RSC Anderlecht (BEL)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'Borussia Dortmund (GER)', 'Galatasaray (TUR)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'Arsenal FC (ENG)', 'Borussia Dortmund (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'RSC Anderlecht (BEL)', 'Galatasaray (TUR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'Galatasaray (TUR)', 'Arsenal FC (ENG)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group D', 'Borussia Dortmund (GER)', 'RSC Anderlecht (BEL)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'AS Roma (ITA)', 'CSKA Moskva (RUS)', '5-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'Bayern München (GER)', 'Manchester City (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'CSKA Moskva (RUS)', 'Bayern München (GER)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'Manchester City (ENG)', 'AS Roma (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'CSKA Moskva (RUS)', 'Manchester City (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'AS Roma (ITA)', 'Bayern München (GER)', '1-7');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'Bayern München (GER)', 'AS Roma (ITA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'Manchester City (ENG)', 'CSKA Moskva (RUS)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'CSKA Moskva (RUS)', 'AS Roma (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'Manchester City (ENG)', 'Bayern München (GER)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'AS Roma (ITA)', 'Manchester City (ENG)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group E', 'Bayern München (GER)', 'CSKA Moskva (RUS)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'AFC Ajax (NED)', 'Paris Saint-Germain (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'FC Barcelona (ESP)', 'APOEL Nikosia (CYP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'APOEL Nikosia (CYP)', 'AFC Ajax (NED)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'Paris Saint-Germain (FRA)', 'FC Barcelona (ESP)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'FC Barcelona (ESP)', 'AFC Ajax (NED)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'APOEL Nikosia (CYP)', 'Paris Saint-Germain (FRA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'AFC Ajax (NED)', 'FC Barcelona (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'Paris Saint-Germain (FRA)', 'APOEL Nikosia (CYP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'Paris Saint-Germain (FRA)', 'AFC Ajax (NED)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'APOEL Nikosia (CYP)', 'FC Barcelona (ESP)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'AFC Ajax (NED)', 'APOEL Nikosia (CYP)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group F', 'FC Barcelona (ESP)', 'Paris Saint-Germain (FRA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'Chelsea FC (ENG)', 'FC Schalke 04 (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'NK Maribor (SVN)', 'Sporting CP (POR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'Sporting CP (POR)', 'Chelsea FC (ENG)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'FC Schalke 04 (GER)', 'NK Maribor (SVN)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'Chelsea FC (ENG)', 'NK Maribor (SVN)', '6-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'FC Schalke 04 (GER)', 'Sporting CP (POR)', '4-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'NK Maribor (SVN)', 'Chelsea FC (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'Sporting CP (POR)', 'FC Schalke 04 (GER)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'FC Schalke 04 (GER)', 'Chelsea FC (ENG)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'Sporting CP (POR)', 'NK Maribor (SVN)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'Chelsea FC (ENG)', 'Sporting CP (POR)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group G', 'NK Maribor (SVN)', 'FC Schalke 04 (GER)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'Athletic Club (ESP)', 'Shakhtar Donetsk (UKR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'FC Porto (POR)', 'BATE Borisov (BLR)', '6-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'BATE Borisov (BLR)', 'Athletic Club (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'Shakhtar Donetsk (UKR)', 'FC Porto (POR)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'FC Porto (POR)', 'Athletic Club (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'BATE Borisov (BLR)', 'Shakhtar Donetsk (UKR)', '0-7');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'Athletic Club (ESP)', 'FC Porto (POR)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'Shakhtar Donetsk (UKR)', 'BATE Borisov (BLR)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'BATE Borisov (BLR)', 'FC Porto (POR)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'Shakhtar Donetsk (UKR)', 'Athletic Club (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'Athletic Club (ESP)', 'BATE Borisov (BLR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Group H', 'FC Porto (POR)', 'Shakhtar Donetsk (UKR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Paris Saint-Germain (FRA)', 'Chelsea FC (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Shakhtar Donetsk (UKR)', 'Bayern München (GER)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'FC Schalke 04 (GER)', 'Real Madrid (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'FC Basel 1893 (SUI)', 'FC Porto (POR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Manchester City (ENG)', 'FC Barcelona (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Juventus (ITA)', 'Borussia Dortmund (GER)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Bayer Leverkusen (GER)', 'Atlético Madrid (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Arsenal FC (ENG)', 'AS Monaco (FRA)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Real Madrid (ESP)', 'FC Schalke 04 (GER)', '3-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'FC Porto (POR)', 'FC Basel 1893 (SUI)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Chelsea FC (ENG)', 'Paris Saint-Germain (FRA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Bayern München (GER)', 'Shakhtar Donetsk (UKR)', '7-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Atlético Madrid (ESP)', 'Bayer Leverkusen (GER)', '1-0(3-2)');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'AS Monaco (FRA)', 'Arsenal FC (ENG)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'FC Barcelona (ESP)', 'Manchester City (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Round of 16', 'Borussia Dortmund (GER)', 'Juventus (ITA)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Quarterfinals', 'Atlético Madrid (ESP)', 'Real Madrid (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Quarterfinals', 'Juventus (ITA)', 'AS Monaco (FRA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Quarterfinals', 'Paris Saint-Germain (FRA)', 'FC Barcelona (ESP)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Quarterfinals', 'FC Porto (POR)', 'Bayern München (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Quarterfinals', 'FC Barcelona (ESP)', 'Paris Saint-Germain (FRA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Quarterfinals', 'Bayern München (GER)', 'FC Porto (POR)', '6-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Quarterfinals', 'Real Madrid (ESP)', 'Atlético Madrid (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Quarterfinals', 'AS Monaco (FRA)', 'Juventus (ITA)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Semifinals', 'Juventus (ITA)', 'Real Madrid (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Semifinals', 'FC Barcelona (ESP)', 'Bayern München (GER)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Semifinals', 'Bayern München (GER)', 'FC Barcelona (ESP)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Semifinals', 'Real Madrid (ESP)', 'Juventus (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2014-2015', 'Final', 'Juventus (ITA)', 'FC Barcelona (ESP)', '1-3');