INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Real Madrid (ESP)', 'Shakhtar Donetsk (UKR)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Paris Saint-Germain (FRA)', 'Malmö FF (SWE)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Malmö FF (SWE)', 'Real Madrid (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Shakhtar Donetsk (UKR)', 'Paris Saint-Germain (FRA)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Paris Saint-Germain (FRA)', 'Real Madrid (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Malmö FF (SWE)', 'Shakhtar Donetsk (UKR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Real Madrid (ESP)', 'Paris Saint-Germain (FRA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Shakhtar Donetsk (UKR)', 'Malmö FF (SWE)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Malmö FF (SWE)', 'Paris Saint-Germain (FRA)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Shakhtar Donetsk (UKR)', 'Real Madrid (ESP)', '3-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Paris Saint-Germain (FRA)', 'Shakhtar Donetsk (UKR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group A', 'Real Madrid (ESP)', 'Malmö FF (SWE)', '8-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'VfL Wolfsburg (GER)', 'CSKA Moskva (RUS)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'PSV Eindhoven (NED)', 'Manchester United (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'CSKA Moskva (RUS)', 'PSV Eindhoven (NED)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'Manchester United (ENG)', 'VfL Wolfsburg (GER)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'CSKA Moskva (RUS)', 'Manchester United (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'VfL Wolfsburg (GER)', 'PSV Eindhoven (NED)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'PSV Eindhoven (NED)', 'VfL Wolfsburg (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'Manchester United (ENG)', 'CSKA Moskva (RUS)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'CSKA Moskva (RUS)', 'VfL Wolfsburg (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'Manchester United (ENG)', 'PSV Eindhoven (NED)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'VfL Wolfsburg (GER)', 'Manchester United (ENG)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group B', 'PSV Eindhoven (NED)', 'CSKA Moskva (RUS)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'SL Benfica (POR)', 'FK Astana (KAZ)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'Galatasaray (TUR)', 'Atlético Madrid (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'FK Astana (KAZ)', 'Galatasaray (TUR)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'Atlético Madrid (ESP)', 'SL Benfica (POR)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'Galatasaray (TUR)', 'SL Benfica (POR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'Atlético Madrid (ESP)', 'FK Astana (KAZ)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'FK Astana (KAZ)', 'Atlético Madrid (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'SL Benfica (POR)', 'Galatasaray (TUR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'FK Astana (KAZ)', 'SL Benfica (POR)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'Atlético Madrid (ESP)', 'Galatasaray (TUR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'Galatasaray (TUR)', 'FK Astana (KAZ)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group C', 'SL Benfica (POR)', 'Atlético Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Sevilla FC (ESP)', 'Bor. Mönchengladbach (GER)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Manchester City (ENG)', 'Juventus (ITA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Juventus (ITA)', 'Sevilla FC (ESP)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Bor. Mönchengladbach (GER)', 'Manchester City (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Manchester City (ENG)', 'Sevilla FC (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Juventus (ITA)', 'Bor. Mönchengladbach (GER)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Bor. Mönchengladbach (GER)', 'Juventus (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Sevilla FC (ESP)', 'Manchester City (ENG)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Juventus (ITA)', 'Manchester City (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Bor. Mönchengladbach (GER)', 'Sevilla FC (ESP)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Manchester City (ENG)', 'Bor. Mönchengladbach (GER)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group D', 'Sevilla FC (ESP)', 'Juventus (ITA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'AS Roma (ITA)', 'FC Barcelona (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'Bayer Leverkusen (GER)', 'BATE Borisov (BLR)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'FC Barcelona (ESP)', 'Bayer Leverkusen (GER)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'BATE Borisov (BLR)', 'AS Roma (ITA)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'BATE Borisov (BLR)', 'FC Barcelona (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'Bayer Leverkusen (GER)', 'AS Roma (ITA)', '4-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'AS Roma (ITA)', 'Bayer Leverkusen (GER)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'FC Barcelona (ESP)', 'BATE Borisov (BLR)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'BATE Borisov (BLR)', 'Bayer Leverkusen (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'FC Barcelona (ESP)', 'AS Roma (ITA)', '6-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'Bayer Leverkusen (GER)', 'FC Barcelona (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group E', 'AS Roma (ITA)', 'BATE Borisov (BLR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Olympiakos Piraeus (GRE)', 'Bayern München (GER)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Dinamo Zagreb (CRO)', 'Arsenal FC (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Arsenal FC (ENG)', 'Olympiakos Piraeus (GRE)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Bayern München (GER)', 'Dinamo Zagreb (CRO)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Arsenal FC (ENG)', 'Bayern München (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Dinamo Zagreb (CRO)', 'Olympiakos Piraeus (GRE)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Bayern München (GER)', 'Arsenal FC (ENG)', '5-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Olympiakos Piraeus (GRE)', 'Dinamo Zagreb (CRO)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Bayern München (GER)', 'Olympiakos Piraeus (GRE)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Arsenal FC (ENG)', 'Dinamo Zagreb (CRO)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Dinamo Zagreb (CRO)', 'Bayern München (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group F', 'Olympiakos Piraeus (GRE)', 'Arsenal FC (ENG)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'Dinamo Kiev (UKR)', 'FC Porto (POR)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'Chelsea FC (ENG)', 'Maccabi Tel Aviv (ISR)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'FC Porto (POR)', 'Chelsea FC (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'Maccabi Tel Aviv (ISR)', 'Dinamo Kiev (UKR)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'FC Porto (POR)', 'Maccabi Tel Aviv (ISR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'Dinamo Kiev (UKR)', 'Chelsea FC (ENG)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'Chelsea FC (ENG)', 'Dinamo Kiev (UKR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'Maccabi Tel Aviv (ISR)', 'FC Porto (POR)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'Maccabi Tel Aviv (ISR)', 'Chelsea FC (ENG)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'FC Porto (POR)', 'Dinamo Kiev (UKR)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'Chelsea FC (ENG)', 'FC Porto (POR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group G', 'Dinamo Kiev (UKR)', 'Maccabi Tel Aviv (ISR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'Valencia CF (ESP)', 'Zenit St. Petersburg (RUS)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'KAA Gent (BEL)', 'Olympique Lyonnais (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'Olympique Lyonnais (FRA)', 'Valencia CF (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'Zenit St. Petersburg (RUS)', 'KAA Gent (BEL)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'Valencia CF (ESP)', 'KAA Gent (BEL)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'Zenit St. Petersburg (RUS)', 'Olympique Lyonnais (FRA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'Olympique Lyonnais (FRA)', 'Zenit St. Petersburg (RUS)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'KAA Gent (BEL)', 'Valencia CF (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'Zenit St. Petersburg (RUS)', 'Valencia CF (ESP)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'Olympique Lyonnais (FRA)', 'KAA Gent (BEL)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'Valencia CF (ESP)', 'Olympique Lyonnais (FRA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Group H', 'KAA Gent (BEL)', 'Zenit St. Petersburg (RUS)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'Paris Saint-Germain (FRA)', 'Chelsea FC (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'SL Benfica (POR)', 'Zenit St. Petersburg (RUS)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'KAA Gent (BEL)', 'VfL Wolfsburg (GER)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'AS Roma (ITA)', 'Real Madrid (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'Arsenal FC (ENG)', 'FC Barcelona (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'Juventus (ITA)', 'Bayern München (GER)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'PSV Eindhoven (NED)', 'Atlético Madrid (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'Dinamo Kiev (UKR)', 'Manchester City (ENG)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'VfL Wolfsburg (GER)', 'KAA Gent (BEL)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'Real Madrid (ESP)', 'AS Roma (ITA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'Zenit St. Petersburg (RUS)', 'SL Benfica (POR)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'Chelsea FC (ENG)', 'Paris Saint-Germain (FRA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'Atlético Madrid (ESP)', 'PSV Eindhoven (NED)', '8-7');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'Manchester City (ENG)', 'Dinamo Kiev (UKR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'FC Barcelona (ESP)', 'Arsenal FC (ENG)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Round of 16', 'Bayern München (GER)', 'Juventus (ITA)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Quarterfinals', 'Bayern München (GER)', 'SL Benfica (POR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Quarterfinals', 'FC Barcelona (ESP)', 'Atlético Madrid (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Quarterfinals', 'VfL Wolfsburg (GER)', 'Real Madrid (ESP)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Quarterfinals', 'Paris Saint-Germain (FRA)', 'Manchester City (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Quarterfinals', 'Real Madrid (ESP)', 'VfL Wolfsburg (GER)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Quarterfinals', 'Manchester City (ENG)', 'Paris Saint-Germain (FRA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Quarterfinals', 'SL Benfica (POR)', 'Bayern München (GER)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Quarterfinals', 'Atlético Madrid (ESP)', 'FC Barcelona (ESP)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Semifinals', 'Manchester City (ENG)', 'Real Madrid (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Semifinals', 'Atlético Madrid (ESP)', 'Bayern München (GER)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Semifinals', 'Bayern München (GER)', 'Atlético Madrid (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Semifinals', 'Real Madrid (ESP)', 'Manchester City (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2015-2016', 'Final', 'Real Madrid (ESP)', 'Atlético Madrid (ESP)', '5-3');