INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'FC Basel 1893 (SUI)', 'PFC Ludogorets Razgrad (BUL)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'Paris Saint-Germain (FRA)', 'Arsenal FC (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'Arsenal FC (ENG)', 'FC Basel 1893 (SUI)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'PFC Ludogorets Razgrad (BUL)', 'Paris Saint-Germain (FRA)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'Arsenal FC (ENG)', 'PFC Ludogorets Razgrad (BUL)', '6-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'Paris Saint-Germain (FRA)', 'FC Basel 1893 (SUI)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'FC Basel 1893 (SUI)', 'Paris Saint-Germain (FRA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'PFC Ludogorets Razgrad (BUL)', 'Arsenal FC (ENG)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'Arsenal FC (ENG)', 'Paris Saint-Germain (FRA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'PFC Ludogorets Razgrad (BUL)', 'FC Basel 1893 (SUI)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'FC Basel 1893 (SUI)', 'Arsenal FC (ENG)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group A', 'Paris Saint-Germain (FRA)', 'PFC Ludogorets Razgrad (BUL)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'Dinamo Kiev (UKR)', 'SSC Napoli (ITA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'SL Benfica (POR)', 'Beşiktaş (TUR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'Beşiktaş (TUR)', 'Dinamo Kiev (UKR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'SSC Napoli (ITA)', 'SL Benfica (POR)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'Dinamo Kiev (UKR)', 'SL Benfica (POR)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'SSC Napoli (ITA)', 'Beşiktaş (TUR)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'Beşiktaş (TUR)', 'SSC Napoli (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'SL Benfica (POR)', 'Dinamo Kiev (UKR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'Beşiktaş (TUR)', 'SL Benfica (POR)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'SSC Napoli (ITA)', 'Dinamo Kiev (UKR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'Dinamo Kiev (UKR)', 'Beşiktaş (TUR)', '6-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group B', 'SL Benfica (POR)', 'SSC Napoli (ITA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'FC Barcelona (ESP)', 'Celtic FC (SCO)', '7-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'Manchester City (ENG)', 'Bor. Mönchengladbach (GER)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'Bor. Mönchengladbach (GER)', 'FC Barcelona (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'Celtic FC (SCO)', 'Manchester City (ENG)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'Celtic FC (SCO)', 'Bor. Mönchengladbach (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'FC Barcelona (ESP)', 'Manchester City (ENG)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'Bor. Mönchengladbach (GER)', 'Celtic FC (SCO)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'Manchester City (ENG)', 'FC Barcelona (ESP)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'Bor. Mönchengladbach (GER)', 'Manchester City (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'Celtic FC (SCO)', 'FC Barcelona (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'FC Barcelona (ESP)', 'Bor. Mönchengladbach (GER)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group C', 'Manchester City (ENG)', 'Celtic FC (SCO)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'Bayern München (GER)', 'FK Rostov (RUS)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'PSV Eindhoven (NED)', 'Atlético Madrid (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'Atlético Madrid (ESP)', 'Bayern München (GER)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'FK Rostov (RUS)', 'PSV Eindhoven (NED)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'Bayern München (GER)', 'PSV Eindhoven (NED)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'FK Rostov (RUS)', 'Atlético Madrid (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'Atlético Madrid (ESP)', 'FK Rostov (RUS)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'PSV Eindhoven (NED)', 'Bayern München (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'FK Rostov (RUS)', 'Bayern München (GER)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'Atlético Madrid (ESP)', 'PSV Eindhoven (NED)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'Bayern München (GER)', 'Atlético Madrid (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group D', 'PSV Eindhoven (NED)', 'FK Rostov (RUS)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'Bayer Leverkusen (GER)', 'CSKA Moskva (RUS)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'Tottenham Hotspur (ENG)', 'AS Monaco (FRA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'AS Monaco (FRA)', 'Bayer Leverkusen (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'CSKA Moskva (RUS)', 'Tottenham Hotspur (ENG)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'Bayer Leverkusen (GER)', 'Tottenham Hotspur (ENG)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'CSKA Moskva (RUS)', 'AS Monaco (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'AS Monaco (FRA)', 'CSKA Moskva (RUS)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'Tottenham Hotspur (ENG)', 'Bayer Leverkusen (GER)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'CSKA Moskva (RUS)', 'Bayer Leverkusen (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'AS Monaco (FRA)', 'Tottenham Hotspur (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'Bayer Leverkusen (GER)', 'AS Monaco (FRA)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group E', 'Tottenham Hotspur (ENG)', 'CSKA Moskva (RUS)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Legia Warszawa (POL)', 'Borussia Dortmund (GER)', '0-6');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Real Madrid (ESP)', 'Sporting CP (POR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Borussia Dortmund (GER)', 'Real Madrid (ESP)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Sporting CP (POR)', 'Legia Warszawa (POL)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Real Madrid (ESP)', 'Legia Warszawa (POL)', '5-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Sporting CP (POR)', 'Borussia Dortmund (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Borussia Dortmund (GER)', 'Sporting CP (POR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Legia Warszawa (POL)', 'Real Madrid (ESP)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Borussia Dortmund (GER)', 'Legia Warszawa (POL)', '8-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Sporting CP (POR)', 'Real Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Legia Warszawa (POL)', 'Sporting CP (POR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group F', 'Real Madrid (ESP)', 'Borussia Dortmund (GER)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'Club Brugge KV (BEL)', 'Leicester City (ENG)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'FC Porto (POR)', 'FC København (DEN)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'FC København (DEN)', 'Club Brugge KV (BEL)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'Leicester City (ENG)', 'FC Porto (POR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'Club Brugge KV (BEL)', 'FC Porto (POR)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'Leicester City (ENG)', 'FC København (DEN)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'FC København (DEN)', 'Leicester City (ENG)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'FC Porto (POR)', 'Club Brugge KV (BEL)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'FC København (DEN)', 'FC Porto (POR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'Leicester City (ENG)', 'Club Brugge KV (BEL)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'Club Brugge KV (BEL)', 'FC København (DEN)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group G', 'FC Porto (POR)', 'Leicester City (ENG)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Juventus (ITA)', 'Sevilla FC (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Olympique Lyonnais (FRA)', 'Dinamo Zagreb (CRO)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Dinamo Zagreb (CRO)', 'Juventus (ITA)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Sevilla FC (ESP)', 'Olympique Lyonnais (FRA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Dinamo Zagreb (CRO)', 'Sevilla FC (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Olympique Lyonnais (FRA)', 'Juventus (ITA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Juventus (ITA)', 'Olympique Lyonnais (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Sevilla FC (ESP)', 'Dinamo Zagreb (CRO)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Dinamo Zagreb (CRO)', 'Olympique Lyonnais (FRA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Sevilla FC (ESP)', 'Juventus (ITA)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Juventus (ITA)', 'Dinamo Zagreb (CRO)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Group H', 'Olympique Lyonnais (FRA)', 'Sevilla FC (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'SL Benfica (POR)', 'Borussia Dortmund (GER)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Paris Saint-Germain (FRA)', 'FC Barcelona (ESP)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Real Madrid (ESP)', 'SSC Napoli (ITA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Bayern München (GER)', 'Arsenal FC (ENG)', '5-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Manchester City (ENG)', 'AS Monaco (FRA)', '5-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Bayer Leverkusen (GER)', 'Atlético Madrid (ESP)', '2-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'FC Porto (POR)', 'Juventus (ITA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Sevilla FC (ESP)', 'Leicester City (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'SSC Napoli (ITA)', 'Real Madrid (ESP)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Arsenal FC (ENG)', 'Bayern München (GER)', '1-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Borussia Dortmund (GER)', 'SL Benfica (POR)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'FC Barcelona (ESP)', 'Paris Saint-Germain (FRA)', '6-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Juventus (ITA)', 'FC Porto (POR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Leicester City (ENG)', 'Sevilla FC (ESP)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'AS Monaco (FRA)', 'Manchester City (ENG)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Round of 16', 'Atlético Madrid (ESP)', 'Bayer Leverkusen (GER)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Quarterfinals', 'Juventus (ITA)', 'FC Barcelona (ESP)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Quarterfinals', 'Borussia Dortmund (GER)', 'AS Monaco (FRA)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Quarterfinals', 'Atlético Madrid (ESP)', 'Leicester City (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Quarterfinals', 'Bayern München (GER)', 'Real Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Quarterfinals', 'Leicester City (ENG)', 'Atlético Madrid (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Quarterfinals', 'Real Madrid (ESP)', 'Bayern München (GER)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Quarterfinals', 'FC Barcelona (ESP)', 'Juventus (ITA)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Quarterfinals', 'AS Monaco (FRA)', 'Borussia Dortmund (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Semifinals', 'Real Madrid (ESP)', 'Atlético Madrid (ESP)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Semifinals', 'AS Monaco (FRA)', 'Juventus (ITA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Semifinals', 'Juventus (ITA)', 'AS Monaco (FRA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Semifinals', 'Atlético Madrid (ESP)', 'Real Madrid (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2016-2017', 'Final', 'Juventus (ITA)', 'Real Madrid (ESP)', '1-4');