INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'Manchester United (ENG)', 'FC Basel 1893 (SUI)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'SL Benfica (POR)', 'CSKA Moskva (RUS)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'FC Basel 1893 (SUI)', 'SL Benfica (POR)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'CSKA Moskva (RUS)', 'Manchester United (ENG)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'SL Benfica (POR)', 'Manchester United (ENG)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'CSKA Moskva (RUS)', 'FC Basel 1893 (SUI)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'Manchester United (ENG)', 'SL Benfica (POR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'FC Basel 1893 (SUI)', 'CSKA Moskva (RUS)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'CSKA Moskva (RUS)', 'SL Benfica (POR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'FC Basel 1893 (SUI)', 'Manchester United (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'SL Benfica (POR)', 'FC Basel 1893 (SUI)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group A', 'Manchester United (ENG)', 'CSKA Moskva (RUS)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'Bayern München (GER)', 'RSC Anderlecht (BEL)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'Celtic FC (SCO)', 'Paris Saint-Germain (FRA)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'Paris Saint-Germain (FRA)', 'Bayern München (GER)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'RSC Anderlecht (BEL)', 'Celtic FC (SCO)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'RSC Anderlecht (BEL)', 'Paris Saint-Germain (FRA)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'Bayern München (GER)', 'Celtic FC (SCO)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'Paris Saint-Germain (FRA)', 'RSC Anderlecht (BEL)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'Celtic FC (SCO)', 'Bayern München (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'RSC Anderlecht (BEL)', 'Bayern München (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'Paris Saint-Germain (FRA)', 'Celtic FC (SCO)', '7-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'Bayern München (GER)', 'Paris Saint-Germain (FRA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group B', 'Celtic FC (SCO)', 'RSC Anderlecht (BEL)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'AS Roma (ITA)', 'Atlético Madrid (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'Chelsea FC (ENG)', 'Qarabağ FK (AZE)', '6-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'Qarabağ FK (AZE)', 'AS Roma (ITA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'Atlético Madrid (ESP)', 'Chelsea FC (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'Qarabağ FK (AZE)', 'Atlético Madrid (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'Chelsea FC (ENG)', 'AS Roma (ITA)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'AS Roma (ITA)', 'Chelsea FC (ENG)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'Atlético Madrid (ESP)', 'Qarabağ FK (AZE)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'Qarabağ FK (AZE)', 'Chelsea FC (ENG)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'Atlético Madrid (ESP)', 'AS Roma (ITA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'Chelsea FC (ENG)', 'Atlético Madrid (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group C', 'AS Roma (ITA)', 'Qarabağ FK (AZE)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'FC Barcelona (ESP)', 'Juventus (ITA)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'Olympiakos Piraeus (GRE)', 'Sporting CP (POR)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'Juventus (ITA)', 'Olympiakos Piraeus (GRE)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'Sporting CP (POR)', 'FC Barcelona (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'FC Barcelona (ESP)', 'Olympiakos Piraeus (GRE)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'Juventus (ITA)', 'Sporting CP (POR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'Olympiakos Piraeus (GRE)', 'FC Barcelona (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'Sporting CP (POR)', 'Juventus (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'Juventus (ITA)', 'FC Barcelona (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'Sporting CP (POR)', 'Olympiakos Piraeus (GRE)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'FC Barcelona (ESP)', 'Sporting CP (POR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group D', 'Olympiakos Piraeus (GRE)', 'Juventus (ITA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'Liverpool FC (ENG)', 'Sevilla FC (ESP)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'NK Maribor (SVN)', 'Spartak Moskva (RUS)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'Spartak Moskva (RUS)', 'Liverpool FC (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'Sevilla FC (ESP)', 'NK Maribor (SVN)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'Spartak Moskva (RUS)', 'Sevilla FC (ESP)', '5-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'NK Maribor (SVN)', 'Liverpool FC (ENG)', '0-7');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'Sevilla FC (ESP)', 'Spartak Moskva (RUS)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'Liverpool FC (ENG)', 'NK Maribor (SVN)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'Spartak Moskva (RUS)', 'NK Maribor (SVN)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'Sevilla FC (ESP)', 'Liverpool FC (ENG)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'Liverpool FC (ENG)', 'Spartak Moskva (RUS)', '7-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group E', 'NK Maribor (SVN)', 'Sevilla FC (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'Shakhtar Donetsk (UKR)', 'SSC Napoli (ITA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'Feyenoord (NED)', 'Manchester City (ENG)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'Manchester City (ENG)', 'Shakhtar Donetsk (UKR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'SSC Napoli (ITA)', 'Feyenoord (NED)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'Manchester City (ENG)', 'SSC Napoli (ITA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'Feyenoord (NED)', 'Shakhtar Donetsk (UKR)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'SSC Napoli (ITA)', 'Manchester City (ENG)', '2-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'Shakhtar Donetsk (UKR)', 'Feyenoord (NED)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'SSC Napoli (ITA)', 'Shakhtar Donetsk (UKR)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'Manchester City (ENG)', 'Feyenoord (NED)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'Shakhtar Donetsk (UKR)', 'Manchester City (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group F', 'Feyenoord (NED)', 'SSC Napoli (ITA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'FC Porto (POR)', 'Beşiktaş (TUR)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'RB Leipzig (GER)', 'AS Monaco (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'AS Monaco (FRA)', 'FC Porto (POR)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'Beşiktaş (TUR)', 'RB Leipzig (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'AS Monaco (FRA)', 'Beşiktaş (TUR)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'RB Leipzig (GER)', 'FC Porto (POR)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'Beşiktaş (TUR)', 'AS Monaco (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'FC Porto (POR)', 'RB Leipzig (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'Beşiktaş (TUR)', 'FC Porto (POR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'AS Monaco (FRA)', 'RB Leipzig (GER)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'FC Porto (POR)', 'AS Monaco (FRA)', '5-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group G', 'RB Leipzig (GER)', 'Beşiktaş (TUR)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'Tottenham Hotspur (ENG)', 'Borussia Dortmund (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'Real Madrid (ESP)', 'APOEL Nikosia (CYP)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'Borussia Dortmund (GER)', 'Real Madrid (ESP)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'APOEL Nikosia (CYP)', 'Tottenham Hotspur (ENG)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'Real Madrid (ESP)', 'Tottenham Hotspur (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'APOEL Nikosia (CYP)', 'Borussia Dortmund (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'Tottenham Hotspur (ENG)', 'Real Madrid (ESP)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'Borussia Dortmund (GER)', 'APOEL Nikosia (CYP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'Borussia Dortmund (GER)', 'Tottenham Hotspur (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'APOEL Nikosia (CYP)', 'Real Madrid (ESP)', '0-6');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'Real Madrid (ESP)', 'Borussia Dortmund (GER)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Group H', 'Tottenham Hotspur (ENG)', 'APOEL Nikosia (CYP)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Juventus (ITA)', 'Tottenham Hotspur (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'FC Basel 1893 (SUI)', 'Manchester City (ENG)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'FC Porto (POR)', 'Liverpool FC (ENG)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Real Madrid (ESP)', 'Paris Saint-Germain (FRA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Chelsea FC (ENG)', 'FC Barcelona (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Bayern München (GER)', 'Beşiktaş (TUR)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Sevilla FC (ESP)', 'Manchester United (ENG)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Shakhtar Donetsk (UKR)', 'AS Roma (ITA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Liverpool FC (ENG)', 'FC Porto (POR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Paris Saint-Germain (FRA)', 'Real Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Tottenham Hotspur (ENG)', 'Juventus (ITA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Manchester City (ENG)', 'FC Basel 1893 (SUI)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Manchester United (ENG)', 'Sevilla FC (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'AS Roma (ITA)', 'Shakhtar Donetsk (UKR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'Beşiktaş (TUR)', 'Bayern München (GER)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Round of 16', 'FC Barcelona (ESP)', 'Chelsea FC (ENG)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Quarterfinals', 'Sevilla FC (ESP)', 'Bayern München (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Quarterfinals', 'Juventus (ITA)', 'Real Madrid (ESP)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Quarterfinals', 'FC Barcelona (ESP)', 'AS Roma (ITA)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Quarterfinals', 'Liverpool FC (ENG)', 'Manchester City (ENG)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Quarterfinals', 'AS Roma (ITA)', 'FC Barcelona (ESP)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Quarterfinals', 'Manchester City (ENG)', 'Liverpool FC (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Quarterfinals', 'Bayern München (GER)', 'Sevilla FC (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Quarterfinals', 'Real Madrid (ESP)', 'Juventus (ITA)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Semifinals', 'Liverpool FC (ENG)', 'AS Roma (ITA)', '5-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Semifinals', 'Bayern München (GER)', 'Real Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Semifinals', 'Real Madrid (ESP)', 'Bayern München (GER)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Semifinals', 'AS Roma (ITA)', 'Liverpool FC (ENG)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2017-2018', 'Final', 'Real Madrid (ESP)', 'Liverpool FC (ENG)', '3-1');