INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'AS Monaco (FRA)', 'Atlético Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'Club Brugge KV (BEL)', 'Borussia Dortmund (GER)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'Borussia Dortmund (GER)', 'AS Monaco (FRA)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'Atlético Madrid (ESP)', 'Club Brugge KV (BEL)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'Club Brugge KV (BEL)', 'AS Monaco (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'Borussia Dortmund (GER)', 'Atlético Madrid (ESP)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'AS Monaco (FRA)', 'Club Brugge KV (BEL)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'Atlético Madrid (ESP)', 'Borussia Dortmund (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'Atlético Madrid (ESP)', 'AS Monaco (FRA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'Borussia Dortmund (GER)', 'Club Brugge KV (BEL)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'AS Monaco (FRA)', 'Borussia Dortmund (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group A', 'Club Brugge KV (BEL)', 'Atlético Madrid (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'FC Barcelona (ESP)', 'PSV Eindhoven (NED)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'Inter (ITA)', 'Tottenham Hotspur (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'Tottenham Hotspur (ENG)', 'FC Barcelona (ESP)', '2-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'PSV Eindhoven (NED)', 'Inter (ITA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'PSV Eindhoven (NED)', 'Tottenham Hotspur (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'FC Barcelona (ESP)', 'Inter (ITA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'Tottenham Hotspur (ENG)', 'PSV Eindhoven (NED)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'Inter (ITA)', 'FC Barcelona (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'PSV Eindhoven (NED)', 'FC Barcelona (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'Tottenham Hotspur (ENG)', 'Inter (ITA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'FC Barcelona (ESP)', 'Tottenham Hotspur (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group B', 'Inter (ITA)', 'PSV Eindhoven (NED)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'Liverpool FC (ENG)', 'Paris Saint-Germain (FRA)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'Crvena Zvezda (SRB)', 'SSC Napoli (ITA)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'Paris Saint-Germain (FRA)', 'Crvena Zvezda (SRB)', '6-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'SSC Napoli (ITA)', 'Liverpool FC (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'Paris Saint-Germain (FRA)', 'SSC Napoli (ITA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'Liverpool FC (ENG)', 'Crvena Zvezda (SRB)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'Crvena Zvezda (SRB)', 'Liverpool FC (ENG)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'SSC Napoli (ITA)', 'Paris Saint-Germain (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'Paris Saint-Germain (FRA)', 'Liverpool FC (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'SSC Napoli (ITA)', 'Crvena Zvezda (SRB)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'Liverpool FC (ENG)', 'SSC Napoli (ITA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group C', 'Crvena Zvezda (SRB)', 'Paris Saint-Germain (FRA)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'FC Schalke 04 (GER)', 'FC Porto (POR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'Galatasaray (TUR)', 'Lokomotiv Moskva (RUS)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'Lokomotiv Moskva (RUS)', 'FC Schalke 04 (GER)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'FC Porto (POR)', 'Galatasaray (TUR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'Lokomotiv Moskva (RUS)', 'FC Porto (POR)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'Galatasaray (TUR)', 'FC Schalke 04 (GER)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'FC Porto (POR)', 'Lokomotiv Moskva (RUS)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'FC Schalke 04 (GER)', 'Galatasaray (TUR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'Lokomotiv Moskva (RUS)', 'Galatasaray (TUR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'FC Porto (POR)', 'FC Schalke 04 (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'FC Schalke 04 (GER)', 'Lokomotiv Moskva (RUS)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group D', 'Galatasaray (TUR)', 'FC Porto (POR)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'AFC Ajax (NED)', 'AEK Athen (GRE)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'SL Benfica (POR)', 'Bayern München (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'Bayern München (GER)', 'AFC Ajax (NED)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'AEK Athen (GRE)', 'SL Benfica (POR)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'AEK Athen (GRE)', 'Bayern München (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'AFC Ajax (NED)', 'SL Benfica (POR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'SL Benfica (POR)', 'AFC Ajax (NED)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'Bayern München (GER)', 'AEK Athen (GRE)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'AEK Athen (GRE)', 'AFC Ajax (NED)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'Bayern München (GER)', 'SL Benfica (POR)', '5-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'AFC Ajax (NED)', 'Bayern München (GER)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group E', 'SL Benfica (POR)', 'AEK Athen (GRE)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', 'Shakhtar Donetsk (UKR)', '1899 Hoffenheim (GER)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', 'Manchester City (ENG)', 'Olympique Lyonnais (FRA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', '1899 Hoffenheim (GER)', 'Manchester City (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', 'Olympique Lyonnais (FRA)', 'Shakhtar Donetsk (UKR)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', 'Shakhtar Donetsk (UKR)', 'Manchester City (ENG)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', '1899 Hoffenheim (GER)', 'Olympique Lyonnais (FRA)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', 'Manchester City (ENG)', 'Shakhtar Donetsk (UKR)', '6-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', 'Olympique Lyonnais (FRA)', '1899 Hoffenheim (GER)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', 'Olympique Lyonnais (FRA)', 'Manchester City (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', '1899 Hoffenheim (GER)', 'Shakhtar Donetsk (UKR)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', 'Shakhtar Donetsk (UKR)', 'Olympique Lyonnais (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group F', 'Manchester City (ENG)', '1899 Hoffenheim (GER)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'Real Madrid (ESP)', 'AS Roma (ITA)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'Viktoria Plzeň (CZE)', 'CSKA Moskva (RUS)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'CSKA Moskva (RUS)', 'Real Madrid (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'AS Roma (ITA)', 'Viktoria Plzeň (CZE)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'AS Roma (ITA)', 'CSKA Moskva (RUS)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'Real Madrid (ESP)', 'Viktoria Plzeň (CZE)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'CSKA Moskva (RUS)', 'AS Roma (ITA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'Viktoria Plzeň (CZE)', 'Real Madrid (ESP)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'CSKA Moskva (RUS)', 'Viktoria Plzeň (CZE)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'AS Roma (ITA)', 'Real Madrid (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'Real Madrid (ESP)', 'CSKA Moskva (RUS)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group G', 'Viktoria Plzeň (CZE)', 'AS Roma (ITA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'Valencia CF (ESP)', 'Juventus (ITA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'BSC Young Boys (SUI)', 'Manchester United (ENG)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'Juventus (ITA)', 'BSC Young Boys (SUI)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'Manchester United (ENG)', 'Valencia CF (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'BSC Young Boys (SUI)', 'Valencia CF (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'Manchester United (ENG)', 'Juventus (ITA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'Valencia CF (ESP)', 'BSC Young Boys (SUI)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'Juventus (ITA)', 'Manchester United (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'Juventus (ITA)', 'Valencia CF (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'Manchester United (ENG)', 'BSC Young Boys (SUI)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'Valencia CF (ESP)', 'Manchester United (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Group H', 'BSC Young Boys (SUI)', 'Juventus (ITA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Manchester United (ENG)', 'Paris Saint-Germain (FRA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'AS Roma (ITA)', 'FC Porto (POR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Tottenham Hotspur (ENG)', 'Borussia Dortmund (GER)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'AFC Ajax (NED)', 'Real Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Olympique Lyonnais (FRA)', 'FC Barcelona (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Liverpool FC (ENG)', 'Bayern München (GER)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'FC Schalke 04 (GER)', 'Manchester City (ENG)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Atlético Madrid (ESP)', 'Juventus (ITA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Borussia Dortmund (GER)', 'Tottenham Hotspur (ENG)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Real Madrid (ESP)', 'AFC Ajax (NED)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Paris Saint-Germain (FRA)', 'Manchester United (ENG)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'FC Porto (POR)', 'AS Roma (ITA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Manchester City (ENG)', 'FC Schalke 04 (GER)', '7-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Juventus (ITA)', 'Atlético Madrid (ESP)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'FC Barcelona (ESP)', 'Olympique Lyonnais (FRA)', '5-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Round of 16', 'Bayern München (GER)', 'Liverpool FC (ENG)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Quarterfinals', 'Liverpool FC (ENG)', 'FC Porto (POR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Quarterfinals', 'Tottenham Hotspur (ENG)', 'Manchester City (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Quarterfinals', 'AFC Ajax (NED)', 'Juventus (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Quarterfinals', 'Manchester United (ENG)', 'FC Barcelona (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Quarterfinals', 'Juventus (ITA)', 'AFC Ajax (NED)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Quarterfinals', 'FC Barcelona (ESP)', 'Manchester United (ENG)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Quarterfinals', 'FC Porto (POR)', 'Liverpool FC (ENG)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Quarterfinals', 'Manchester City (ENG)', 'Tottenham Hotspur (ENG)', '4-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Semifinals', 'Tottenham Hotspur (ENG)', 'AFC Ajax (NED)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Semifinals', 'FC Barcelona (ESP)', 'Liverpool FC (ENG)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Semifinals', 'Liverpool FC (ENG)', 'FC Barcelona (ESP)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Semifinals', 'AFC Ajax (NED)', 'Tottenham Hotspur (ENG)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2018-2019', 'Final', 'Tottenham Hotspur (ENG)', 'Liverpool FC (ENG)', '0-2');