INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Club Brugge KV (BEL)', 'Galatasaray (TUR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Paris Saint-Germain (FRA)', 'Real Madrid (ESP)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Real Madrid (ESP)', 'Club Brugge KV (BEL)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Galatasaray (TUR)', 'Paris Saint-Germain (FRA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Club Brugge KV (BEL)', 'Paris Saint-Germain (FRA)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Galatasaray (TUR)', 'Real Madrid (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Paris Saint-Germain (FRA)', 'Club Brugge KV (BEL)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Real Madrid (ESP)', 'Galatasaray (TUR)', '6-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Galatasaray (TUR)', 'Club Brugge KV (BEL)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Real Madrid (ESP)', 'Paris Saint-Germain (FRA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Paris Saint-Germain (FRA)', 'Galatasaray (TUR)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group A', 'Club Brugge KV (BEL)', 'Real Madrid (ESP)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Olympiakos Piraeus (GRE)', 'Tottenham Hotspur (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Bayern München (GER)', 'Crvena Zvezda (SRB)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Tottenham Hotspur (ENG)', 'Bayern München (GER)', '2-7');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Crvena Zvezda (SRB)', 'Olympiakos Piraeus (GRE)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Tottenham Hotspur (ENG)', 'Crvena Zvezda (SRB)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Olympiakos Piraeus (GRE)', 'Bayern München (GER)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Bayern München (GER)', 'Olympiakos Piraeus (GRE)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Crvena Zvezda (SRB)', 'Tottenham Hotspur (ENG)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Tottenham Hotspur (ENG)', 'Olympiakos Piraeus (GRE)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Crvena Zvezda (SRB)', 'Bayern München (GER)', '0-6');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Bayern München (GER)', 'Tottenham Hotspur (ENG)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group B', 'Olympiakos Piraeus (GRE)', 'Crvena Zvezda (SRB)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Shakhtar Donetsk (UKR)', 'Manchester City (ENG)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Dinamo Zagreb (CRO)', 'Atalanta (ITA)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Atalanta (ITA)', 'Shakhtar Donetsk (UKR)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Manchester City (ENG)', 'Dinamo Zagreb (CRO)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Shakhtar Donetsk (UKR)', 'Dinamo Zagreb (CRO)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Manchester City (ENG)', 'Atalanta (ITA)', '5-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Dinamo Zagreb (CRO)', 'Shakhtar Donetsk (UKR)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Atalanta (ITA)', 'Manchester City (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Manchester City (ENG)', 'Shakhtar Donetsk (UKR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Atalanta (ITA)', 'Dinamo Zagreb (CRO)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Shakhtar Donetsk (UKR)', 'Atalanta (ITA)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group C', 'Dinamo Zagreb (CRO)', 'Manchester City (ENG)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Atlético Madrid (ESP)', 'Juventus (ITA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Bayer Leverkusen (GER)', 'Lokomotiv Moskva (RUS)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Juventus (ITA)', 'Bayer Leverkusen (GER)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Lokomotiv Moskva (RUS)', 'Atlético Madrid (ESP)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Atlético Madrid (ESP)', 'Bayer Leverkusen (GER)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Juventus (ITA)', 'Lokomotiv Moskva (RUS)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Lokomotiv Moskva (RUS)', 'Juventus (ITA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Bayer Leverkusen (GER)', 'Atlético Madrid (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Lokomotiv Moskva (RUS)', 'Bayer Leverkusen (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Juventus (ITA)', 'Atlético Madrid (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Atlético Madrid (ESP)', 'Lokomotiv Moskva (RUS)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group D', 'Bayer Leverkusen (GER)', 'Juventus (ITA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'SSC Napoli (ITA)', 'Liverpool FC (ENG)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'RB Salzburg (AUT)', 'KRC Genk (BEL)', '6-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'KRC Genk (BEL)', 'SSC Napoli (ITA)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'Liverpool FC (ENG)', 'RB Salzburg (AUT)', '4-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'RB Salzburg (AUT)', 'SSC Napoli (ITA)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'KRC Genk (BEL)', 'Liverpool FC (ENG)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'Liverpool FC (ENG)', 'KRC Genk (BEL)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'SSC Napoli (ITA)', 'RB Salzburg (AUT)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'Liverpool FC (ENG)', 'SSC Napoli (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'KRC Genk (BEL)', 'RB Salzburg (AUT)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'SSC Napoli (ITA)', 'KRC Genk (BEL)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group E', 'RB Salzburg (AUT)', 'Liverpool FC (ENG)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'Inter (ITA)', 'Slavia Praha (CZE)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'Borussia Dortmund (GER)', 'FC Barcelona (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'Slavia Praha (CZE)', 'Borussia Dortmund (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'FC Barcelona (ESP)', 'Inter (ITA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'Inter (ITA)', 'Borussia Dortmund (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'Slavia Praha (CZE)', 'FC Barcelona (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'FC Barcelona (ESP)', 'Slavia Praha (CZE)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'Borussia Dortmund (GER)', 'Inter (ITA)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'FC Barcelona (ESP)', 'Borussia Dortmund (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'Slavia Praha (CZE)', 'Inter (ITA)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'Borussia Dortmund (GER)', 'Slavia Praha (CZE)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group F', 'Inter (ITA)', 'FC Barcelona (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'Olympique Lyonnais (FRA)', 'Zenit St. Petersburg (RUS)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'SL Benfica (POR)', 'RB Leipzig (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'Zenit St. Petersburg (RUS)', 'SL Benfica (POR)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'RB Leipzig (GER)', 'Olympique Lyonnais (FRA)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'RB Leipzig (GER)', 'Zenit St. Petersburg (RUS)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'SL Benfica (POR)', 'Olympique Lyonnais (FRA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'Zenit St. Petersburg (RUS)', 'RB Leipzig (GER)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'Olympique Lyonnais (FRA)', 'SL Benfica (POR)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'Zenit St. Petersburg (RUS)', 'Olympique Lyonnais (FRA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'RB Leipzig (GER)', 'SL Benfica (POR)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'SL Benfica (POR)', 'Zenit St. Petersburg (RUS)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group G', 'Olympique Lyonnais (FRA)', 'RB Leipzig (GER)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'Chelsea FC (ENG)', 'Valencia CF (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'AFC Ajax (NED)', 'Lille OSC (FRA)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'Valencia CF (ESP)', 'AFC Ajax (NED)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'Lille OSC (FRA)', 'Chelsea FC (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'AFC Ajax (NED)', 'Chelsea FC (ENG)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'Lille OSC (FRA)', 'Valencia CF (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'Chelsea FC (ENG)', 'AFC Ajax (NED)', '4-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'Valencia CF (ESP)', 'Lille OSC (FRA)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'Valencia CF (ESP)', 'Chelsea FC (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'Lille OSC (FRA)', 'AFC Ajax (NED)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'Chelsea FC (ENG)', 'Lille OSC (FRA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Group H', 'AFC Ajax (NED)', 'Valencia CF (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Borussia Dortmund (GER)', 'Paris Saint-Germain (FRA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Atlético Madrid (ESP)', 'Liverpool FC (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Atalanta (ITA)', 'Valencia CF (ESP)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Tottenham Hotspur (ENG)', 'RB Leipzig (GER)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Chelsea FC (ENG)', 'Bayern München (GER)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'SSC Napoli (ITA)', 'FC Barcelona (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Real Madrid (ESP)', 'Manchester City (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Olympique Lyonnais (FRA)', 'Juventus (ITA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Valencia CF (ESP)', 'Atalanta (ITA)', '3-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'RB Leipzig (GER)', 'Tottenham Hotspur (ENG)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Paris Saint-Germain (FRA)', 'Borussia Dortmund (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Liverpool FC (ENG)', 'Atlético Madrid (ESP)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Manchester City (ENG)', 'Real Madrid (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Juventus (ITA)', 'Olympique Lyonnais (FRA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'Bayern München (GER)', 'Chelsea FC (ENG)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Round of 16', 'FC Barcelona (ESP)', 'SSC Napoli (ITA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Quarterfinals', 'Atalanta (ITA)', 'Paris Saint-Germain (FRA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Quarterfinals', 'RB Leipzig (GER)', 'Atlético Madrid (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Quarterfinals', 'FC Barcelona (ESP)', 'Bayern München (GER)', '2-8');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Quarterfinals', 'Manchester City (ENG)', 'Olympique Lyonnais (FRA)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Semifinals', 'RB Leipzig (GER)', 'Paris Saint-Germain (FRA)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Semifinals', 'Olympique Lyonnais (FRA)', 'Bayern München (GER)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2019-2020', 'Final', 'Paris Saint-Germain (FRA)', 'Bayern München (GER)', '0-1');