INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'Manchester City (ENG)', 'RB Leipzig (GER)', '6-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'Club Brugge KV (BEL)', 'Paris Saint-Germain (FRA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'Paris Saint-Germain (FRA)', 'Manchester City (ENG)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'RB Leipzig (GER)', 'Club Brugge KV (BEL)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'Club Brugge KV (BEL)', 'Manchester City (ENG)', '1-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'Paris Saint-Germain (FRA)', 'RB Leipzig (GER)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'RB Leipzig (GER)', 'Paris Saint-Germain (FRA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'Manchester City (ENG)', 'Club Brugge KV (BEL)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'Manchester City (ENG)', 'Paris Saint-Germain (FRA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'Club Brugge KV (BEL)', 'RB Leipzig (GER)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'RB Leipzig (GER)', 'Manchester City (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group A', 'Paris Saint-Germain (FRA)', 'Club Brugge KV (BEL)', '4-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'Atlético Madrid (ESP)', 'FC Porto (POR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'Liverpool FC (ENG)', 'AC Milan (ITA)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'FC Porto (POR)', 'Liverpool FC (ENG)', '1-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'AC Milan (ITA)', 'Atlético Madrid (ESP)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'Atlético Madrid (ESP)', 'Liverpool FC (ENG)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'FC Porto (POR)', 'AC Milan (ITA)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'AC Milan (ITA)', 'FC Porto (POR)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'Liverpool FC (ENG)', 'Atlético Madrid (ESP)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'Liverpool FC (ENG)', 'FC Porto (POR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'Atlético Madrid (ESP)', 'AC Milan (ITA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'FC Porto (POR)', 'Atlético Madrid (ESP)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group B', 'AC Milan (ITA)', 'Liverpool FC (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'Beşiktaş (TUR)', 'Borussia Dortmund (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'Sporting CP (POR)', 'AFC Ajax (NED)', '1-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'AFC Ajax (NED)', 'Beşiktaş (TUR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'Borussia Dortmund (GER)', 'Sporting CP (POR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'Beşiktaş (TUR)', 'Sporting CP (POR)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'AFC Ajax (NED)', 'Borussia Dortmund (GER)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'Borussia Dortmund (GER)', 'AFC Ajax (NED)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'Sporting CP (POR)', 'Beşiktaş (TUR)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'Beşiktaş (TUR)', 'AFC Ajax (NED)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'Sporting CP (POR)', 'Borussia Dortmund (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'AFC Ajax (NED)', 'Sporting CP (POR)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group C', 'Borussia Dortmund (GER)', 'Beşiktaş (TUR)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'FC Sheriff (MDA)', 'Shakhtar Donetsk (UKR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'Inter (ITA)', 'Real Madrid (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'Shakhtar Donetsk (UKR)', 'Inter (ITA)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'Real Madrid (ESP)', 'FC Sheriff (MDA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'Shakhtar Donetsk (UKR)', 'Real Madrid (ESP)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'Inter (ITA)', 'FC Sheriff (MDA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'Real Madrid (ESP)', 'Shakhtar Donetsk (UKR)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'FC Sheriff (MDA)', 'Inter (ITA)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'Inter (ITA)', 'Shakhtar Donetsk (UKR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'FC Sheriff (MDA)', 'Real Madrid (ESP)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'Real Madrid (ESP)', 'Inter (ITA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group D', 'Shakhtar Donetsk (UKR)', 'FC Sheriff (MDA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'FC Barcelona (ESP)', 'Bayern München (GER)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'Dinamo Kiev (UKR)', 'SL Benfica (POR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'SL Benfica (POR)', 'FC Barcelona (ESP)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'Bayern München (GER)', 'Dinamo Kiev (UKR)', '5-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'FC Barcelona (ESP)', 'Dinamo Kiev (UKR)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'SL Benfica (POR)', 'Bayern München (GER)', '0-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'Bayern München (GER)', 'SL Benfica (POR)', '5-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'Dinamo Kiev (UKR)', 'FC Barcelona (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'Dinamo Kiev (UKR)', 'Bayern München (GER)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'FC Barcelona (ESP)', 'SL Benfica (POR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'Bayern München (GER)', 'FC Barcelona (ESP)', '3-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group E', 'SL Benfica (POR)', 'Dinamo Kiev (UKR)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'BSC Young Boys (SUI)', 'Manchester United (ENG)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'Villarreal CF (ESP)', 'Atalanta (ITA)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'Atalanta (ITA)', 'BSC Young Boys (SUI)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'Manchester United (ENG)', 'Villarreal CF (ESP)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'Manchester United (ENG)', 'Atalanta (ITA)', '3-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'BSC Young Boys (SUI)', 'Villarreal CF (ESP)', '1-4');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'Atalanta (ITA)', 'Manchester United (ENG)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'Villarreal CF (ESP)', 'BSC Young Boys (SUI)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'Villarreal CF (ESP)', 'Manchester United (ENG)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'BSC Young Boys (SUI)', 'Atalanta (ITA)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'Manchester United (ENG)', 'BSC Young Boys (SUI)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Group F', 'Atalanta (ITA)', 'Villarreal CF (ESP)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'Sevilla FC (ESP)', 'RB Salzburg (AUT)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'Lille OSC (FRA)', 'VfL Wolfsburg (GER)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'RB Salzburg (AUT)', 'Lille OSC (FRA)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'VfL Wolfsburg (GER)', 'Sevilla FC (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'RB Salzburg (AUT)', 'VfL Wolfsburg (GER)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'Lille OSC (FRA)', 'Sevilla FC (ESP)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'VfL Wolfsburg (GER)', 'RB Salzburg (AUT)', '2-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'Sevilla FC (ESP)', 'Lille OSC (FRA)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'Lille OSC (FRA)', 'RB Salzburg (AUT)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'Sevilla FC (ESP)', 'VfL Wolfsburg (GER)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'RB Salzburg (AUT)', 'Sevilla FC (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe G', 'VfL Wolfsburg (GER)', 'Lille OSC (FRA)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Chelsea FC (ENG)', 'Zenit St. Petersburg (RUS)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Malmö FF (SWE)', 'Juventus (ITA)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Zenit St. Petersburg (RUS)', 'Malmö FF (SWE)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Juventus (ITA)', 'Chelsea FC (ENG)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Zenit St. Petersburg (RUS)', 'Juventus (ITA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Chelsea FC (ENG)', 'Malmö FF (SWE)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Malmö FF (SWE)', 'Chelsea FC (ENG)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Juventus (ITA)', 'Zenit St. Petersburg (RUS)', '4-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Chelsea FC (ENG)', 'Juventus (ITA)', '4-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Malmö FF (SWE)', 'Zenit St. Petersburg (RUS)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Zenit St. Petersburg (RUS)', 'Chelsea FC (ENG)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Gruppe H', 'Juventus (ITA)', 'Malmö FF (SWE)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Sporting CP (POR)', 'Manchester City (ENG)', '0-5');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Paris Saint-Germain (FRA)', 'Real Madrid (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'RB Salzburg (AUT)', 'Bayern München (GER)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Inter (ITA)', 'Liverpool FC (ENG)', '0-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Chelsea FC (ENG)', 'Lille OSC (FRA)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Villarreal CF (ESP)', 'Juventus (ITA)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'SL Benfica (POR)', 'AFC Ajax (NED)', '2-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Atlético Madrid (ESP)', 'Manchester United (ENG)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Bayern München (GER)', 'RB Salzburg (AUT)', '7-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Liverpool FC (ENG)', 'Inter (ITA)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Manchester City (ENG)', 'Sporting CP (POR)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Real Madrid (ESP)', 'Paris Saint-Germain (FRA)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'AFC Ajax (NED)', 'SL Benfica (POR)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Manchester United (ENG)', 'Atlético Madrid (ESP)', '0-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Lille OSC (FRA)', 'Chelsea FC (ENG)', '1-2');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Round of 16', 'Juventus (ITA)', 'Villarreal CF (ESP)', '0-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Quarterfinals', 'Manchester City (ENG)', 'Atlético Madrid (ESP)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Quarterfinals', 'SL Benfica (POR)', 'Liverpool FC (ENG)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Quarterfinals', 'Chelsea FC (ENG)', 'Real Madrid (ESP)', '1-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Quarterfinals', 'Villarreal CF (ESP)', 'Bayern München (GER)', '1-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Quarterfinals', 'Real Madrid (ESP)', 'Chelsea FC (ENG)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Quarterfinals', 'Bayern München (GER)', 'Villarreal CF (ESP)', '1-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Quarterfinals', 'Atlético Madrid (ESP)', 'Manchester City (ENG)', '0-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Quarterfinals', 'Liverpool FC (ENG)', 'SL Benfica (POR)', '3-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Semifinals', 'Manchester City (ENG)', 'Real Madrid (ESP)', '4-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Semifinals', 'Liverpool FC (ENG)', 'Villarreal CF (ESP)', '2-0');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Semifinals', 'Villarreal CF (ESP)', 'Liverpool FC (ENG)', '2-3');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Semifinals', 'Real Madrid (ESP)', 'Manchester City (ENG)', '3-1');
INSERT INTO partidos_ucl (temporada, fase, equipo_local, equipo_visitante, resultado) VALUES ('2021-2022', 'Final', 'Liverpool FC (ENG)', 'Real Madrid (ESP)', '0-1');