INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group A", "Brazil", "Scotland", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group A", "Morocco", "Norway", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group A", "Scotland", "Norway", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group A", "Brazil", "Morocco", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group A", "Scotland", "Morocco", "0-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group A", "Brazil", "Norway", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group B", "Cameroon", "Austria", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group B", "Italy", "Chile", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group B", "Chile", "Austria", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group B", "Italy", "Cameroon", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group B", "Italy", "Austria", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group B", "Chile", "Cameroon", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group C", "Saudi Arabia", "Denmark", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group C", "France", "South Africa", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group C", "France", "Saudi Arabia", "4-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group C", "South Africa", "Denmark", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group C", "France", "Denmark", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group C", "South Africa", "Saudi Arabia", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group D", "Paraguay", "Bulgaria", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group D", "Spain", "Nigeria", "2-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group D", "Nigeria", "Bulgaria", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group D", "Spain", "Paraguay", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group D", "Spain", "Bulgaria", "6-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group D", "Nigeria", "Paraguay", "1-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group E", "Netherlands", "Belgium", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group E", "South Korea", "Mexico", "1-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group E", "Netherlands", "South Korea", "5-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group E", "Belgium", "Mexico", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group E", "Belgium", "South Korea", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group E", "Netherlands", "Mexico", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group F", "Yugoslavia", "Iran", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group F", "Germany", "United States", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group F", "Germany", "Yugoslavia", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group F", "United States", "Iran", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group F", "Germany", "Iran", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group F", "United States", "Yugoslavia", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group G", "Romania", "Colombia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group G", "England", "Tunisia", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group G", "Colombia", "Tunisia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group G", "Romania", "England", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group G", "Romania", "Tunisia", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group G", "Colombia", "England", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group H", "Jamaica", "Croatia", "1-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group H", "Argentina", "Japan", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group H", "Japan", "Croatia", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group H", "Argentina", "Jamaica", "5-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group H", "Japan", "Jamaica", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Group H", "Argentina", "Croatia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Round of 16", "Brazil", "Chile", "4-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Round of 16", "Italy", "Norway", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Round of 16", "Nigeria", "Denmark", "1-4");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Round of 16", "France", "Paraguay", "0-0(1-0)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Round of 16", "Germany", "Mexico", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Round of 16", "Netherlands", "Yugoslavia", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Round of 16", "Argentina", "England", "2-2(4-3)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Round of 16", "Romania", "Croatia", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Quarter-finals", "Italy", "France", "0-0(3-4)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Quarter-finals", "Brazil", "Denmark", "3-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Quarter-finals", "Germany", "Croatia", "0-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Quarter-finals", "Netherlands", "Argentina", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Semi-finals", "Brazil", "Netherlands", "1-1(4-2)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Semi-finals", "France", "Croatia", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Third place play-off", "Netherlands", "Croatia", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("1998", "Final", "Brazil", "France", "0-3");
