INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group A", "France", "Senegal", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group A", "Uruguay", "Denmark", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group A", "France", "Uruguay", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group A", "Denmark", "Senegal", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group A", "Denmark", "France", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group A", "Senegal", "Uruguay", "3-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group B", "Paraguay", "South Africa", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group B", "Spain", "Slovenia", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group B", "Spain", "Paraguay", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group B", "South Africa", "Slovenia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group B", "South Africa", "Spain", "2-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group B", "Slovenia", "Paraguay", "1-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group C", "Brazil", "Turkey", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group C", "China", "Costa Rica", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group C", "Brazil", "China", "4-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group C", "Costa Rica", "Turkey", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group C", "Costa Rica", "Brazil", "2-5");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group C", "Turkey", "China", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group D", "South Korea", "Poland", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group D", "United States", "Portugal", "3-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group D", "South Korea", "United States", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group D", "Portugal", "Poland", "4-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group D", "Portugal", "South Korea", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group D", "Poland", "United States", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group E", "Ireland", "Cameroon", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group E", "Germany", "Saudi Arabia", "8-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group E", "Germany", "Ireland", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group E", "Cameroon", "Saudi Arabia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group E", "Cameroon", "Germany", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group E", "Saudi Arabia", "Ireland", "0-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group F", "England", "Sweden", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group F", "Argentina", "Nigeria", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group F", "Sweden", "Nigeria", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group F", "Argentina", "England", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group F", "Sweden", "Argentina", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group F", "Nigeria", "England", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group G", "Croatia", "Mexico", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group G", "Italy", "Ecuador", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group G", "Italy", "Croatia", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group G", "Mexico", "Ecuador", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group G", "Mexico", "Italy", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group G", "Ecuador", "Croatia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group H", "Japan", "Belgium", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group H", "Russia", "Tunisia", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group H", "Japan", "Russia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group H", "Tunisia", "Belgium", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group H", "Tunisia", "Japan", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Group H", "Belgium", "Russia", "3-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Round of 16", "Germany", "Paraguay", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Round of 16", "Denmark", "England", "0-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Round of 16", "Sweden", "Senegal", "1-1(1-2)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Round of 16", "Spain", "Ireland", "1-1(3-2)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Round of 16", "Mexico", "United States", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Round of 16", "Brazil", "Belgium", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Round of 16", "Japan", "Turkey", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Round of 16", "South Korea", "Italy", "1-1(2-1)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Quarter-finals", "England", "Brazil", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Quarter-finals", "Germany", "United States", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Quarter-finals", "Spain", "South Korea", "0-0(3-5)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Quarter-finals", "Senegal", "Turkey", "0-0(0-1)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Semi-finals", "Germany", "South Korea", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Semi-finals", "Brazil", "Turkey", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Third place play-off", "South Korea", "Turkey", "2-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2002", "Final", "Germany", "Brazil", "0-2");
