INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group A", "Germany", "Costa Rica", "4-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group A", "Poland", "Ecuador", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group A", "Germany", "Poland", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group A", "Ecuador", "Costa Rica", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group A", "Ecuador", "Germany", "0-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group A", "Costa Rica", "Poland", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group B", "England", "Paraguay", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group B", "Trinidad and Tobago", "Sweden", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group B", "England", "Trinidad and Tobago", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group B", "Sweden", "Paraguay", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group B", "Sweden", "England", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group B", "Paraguay", "Trinidad and Tobago", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group C", "Argentina", "Ivory Coast", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group C", "Serbia and Montenegro", "Netherlands", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group C", "Argentina", "Serbia and Montenegro", "6-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group C", "Netherlands", "Ivory Coast", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group C", "Netherlands", "Argentina", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group C", "Ivory Coast", "Serbia and Montenegro", "3-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group D", "Mexico", "Iran", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group D", "Angola", "Portugal", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group D", "Mexico", "Angola", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group D", "Portugal", "Iran", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group D", "Portugal", "Mexico", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group D", "Iran", "Angola", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group E", "Italy", "Ghana", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group E", "United States", "Czech Republic", "0-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group E", "Italy", "United States", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group E", "Czech Republic", "Ghana", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group E", "Czech Republic", "Italy", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group E", "Ghana", "United States", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group F", "Brazil", "Croatia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group F", "Australia", "Japan", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group F", "Brazil", "Australia", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group F", "Japan", "Croatia", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group F", "Japan", "Brazil", "1-4");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group F", "Croatia", "Australia", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group G", "France", "Switzerland", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group G", "South Korea", "Togo", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group G", "France", "South Korea", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group G", "Togo", "Switzerland", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group G", "Togo", "France", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group G", "Switzerland", "South Korea", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group H", "Spain", "Ukraine", "4-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group H", "Tunisia", "Saudi Arabia", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group H", "Spain", "Tunisia", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group H", "Saudi Arabia", "Ukraine", "0-4");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group H", "Saudi Arabia", "Spain", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Group H", "Ukraine", "Tunisia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Round of 16", "Germany", "Sweden", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Round of 16", "Argentina", "Mexico", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Round of 16", "England", "Ecuador", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Round of 16", "Portugal", "Netherlands", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Round of 16", "Italy", "Australia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Round of 16", "Switzerland", "Ukraine", "0-0(0-3)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Round of 16", "Brazil", "Ghana", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Round of 16", "Spain", "France", "1-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Quarterfinals", "Germany", "Argentina", "1-1(4-2)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Quarterfinals", "Italy", "Ukraine", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Quarterfinals", "England", "Portugal", "0-0(1-3)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Quarterfinals", "Brazil", "France", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Semifinals", "Germany", "Italy", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Semifinals", "Portugal", "France", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Third-place play-off", "Germany", "Portugal", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2006", "Final", "Italy", "France", "1-1(5-3)");