INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group A", "Brazil", "Croatia", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group A", "Mexico", "Cameroon", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group A", "Brazil", "Mexico", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group A", "Cameroon", "Croatia", "0-4");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group A", "Cameroon", "Brazil", "1-4");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group A", "Croatia", "Mexico", "1-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group B", "Spain", "Netherlands", "1-5");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group B", "Chile", "Australia", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group B", "Spain", "Chile", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group B", "Australia", "Netherlands", "2-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group B", "Australia", "Spain", "0-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group B", "Netherlands", "Chile", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group C", "Colombia", "Greece", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group C", "Ivory Coast", "Japan", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group C", "Colombia", "Ivory Coast", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group C", "Japan", "Greece", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group C", "Japan", "Colombia", "1-4");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group C", "Greece", "Ivory Coast", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group D", "Uruguay", "Costa Rica", "1-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group D", "England", "Italy", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group D", "Uruguay", "England", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group D", "Italy", "Costa Rica", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group D", "Italy", "Uruguay", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group D", "Costa Rica", "England", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group E", "Switzerland", "Ecuador", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group E", "France", "Honduras", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group E", "Switzerland", "France", "2-5");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group E", "Honduras", "Ecuador", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group E", "Honduras", "Switzerland", "0-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group E", "Ecuador", "France", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group F", "Argentina", "Bosnia Herzegovina", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group F", "Iran", "Nigeria", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group F", "Argentina", "Iran", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group F", "Nigeria", "Bosnia Herzegovina", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group F", "Nigeria", "Argentina", "2-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group F", "Bosnia Herzegovina", "Iran", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group G", "Germany", "Portugal", "4-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group G", "Ghana", "United States", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group G", "Germany", "Ghana", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group G", "United States", "Portugal", "2-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group G", "United States", "Germany", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group G", "Portugal", "Ghana", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group H", "Belgium", "Algeria", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group H", "Russia", "South Korea", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group H", "Belgium", "Russia", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group H", "South Korea", "Algeria", "2-4");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group H", "South Korea", "Belgium", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Group H", "Algeria", "Russia", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Round of 16", "Brazil", "Chile", "1-1(3-2)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Round of 16", "Colombia", "Uruguay", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Round of 16", "Netherlands", "Mexico", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Round of 16", "Costa Rica", "Greece", "1-1(5-3)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Round of 16", "France", "Nigeria", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Round of 16", "Germany", "Algeria", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Round of 16", "Argentina", "Switzerland", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Round of 16", "Belgium", "United States", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Quarter-finals", "Brazil", "Colombia", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Quarter-finals", "France", "Germany", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Quarter-finals", "Netherlands", "Costa Rica", "0-0(4-3)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Quarter-finals", "Argentina", "Belgium", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Semi-finals", "Brazil", "Germany", "1-7");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Semi-finals", "Netherlands", "Argentina", "0-0(2-4)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Match for third place", "Brazil", "Netherlands", "0-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2014", "Final", "Germany", "Argentina", "1-0");