INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group A", "Qatar", "Ecuador", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group A", "Senegal", "Netherlands", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group A", "Qatar", "Senegal", "1-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group A", "Netherlands", "Ecuador", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group A", "Ecuador", "Senegal", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group A", "Netherlands", "Qatar", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group B", "England", "Iran", "6-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group B", "United States", "Wales", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group B", "Wales", "Iran", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group B", "England", "United States", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group B", "Wales", "England", "0-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group B", "Iran", "United States", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group C", "Argentina", "Saudi Arabia", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group C", "Mexico", "Poland", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group C", "Poland", "Saudi Arabia", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group C", "Argentina", "Mexico", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group C", "Poland", "Argentina", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group C", "Saudi Arabia", "Mexico", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group D", "Denmark", "Tunisia", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group D", "France", "Australia", "4-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group D", "Tunisia", "Australia", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group D", "France", "Denmark", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group D", "Australia", "Denmark", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group D", "Tunisia", "France", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group E", "Germany", "Japan", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group E", "Spain", "Costa Rica", "7-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group E", "Japan", "Costa Rica", "0-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group E", "Spain", "Germany", "1-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group E", "Japan", "Spain", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group E", "Costa Rica", "Germany", "2-4");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group F", "Morocco", "Croatia", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group F", "Belgium", "Canada", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group F", "Belgium", "Morocco", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group F", "Croatia", "Canada", "4-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group F", "Croatia", "Belgium", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group F", "Canada", "Morocco", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group G", "Switzerland", "Cameroon", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group G", "Brazil", "Serbia", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group G", "Cameroon", "Serbia", "3-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group G", "Brazil", "Switzerland", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group G", "Serbia", "Switzerland", "2-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group G", "Cameroon", "Brazil", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group H", "Uruguay", "South Korea", "0-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group H", "Portugal", "Ghana", "3-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group H", "South Korea", "Ghana", "2-3");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group H", "Portugal", "Uruguay", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group H", "Ghana", "Uruguay", "0-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Group H", "South Korea", "Portugal", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Round of 16", "Netherlands", "United States", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Round of 16", "Argentina", "Australia", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Round of 16", "France", "Poland", "3-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Round of 16", "England", "Senegal", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Round of 16", "Japan", "Croatia", "1-1(1-3)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Round of 16", "Brazil", "South Korea", "4-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Round of 16", "Morocco", "Spain", "0-0(3-0)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Round of 16", "Portugal", "Switzerland", "6-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Quarter-finals", "Croatia", "Brazil", "1-1(4-2)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Quarter-finals", "Netherlands", "Argentina", "2-2(3-4)");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Quarter-finals", "Morocco", "Portugal", "1-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Quarter-finals", "England", "France", "1-2");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Semi-finals", "Argentina", "Croatia", "3-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Semi-finals", "France", "Morocco", "2-0");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Match for third place", "Croatia", "Morocco", "2-1");
INSERT INTO partidos_mundiales (año, fase, pais1, pais2, resultado) VALUES ("2022", "Final", "Argentina", "France", "3-3(4-2)");